### ISSUE TITLE
multilingual text

### ISSUE THREAD

**Issue by SnelleJelle** [howest-wsde/VrijwilligersTool#100]
Some constraints have static messages. These need to be converted to messages from the validation files

**Comment by SnelleJelle** [comment]
Even vermelden dat dit de 100ste issue is!!! FEEST! :tada: :balloon: :fireworks: :birthday: :dancer: :dancers:

**Comment by Badlapje** [comment]
- alle forms ok

**Comment by Badlapje** [comment]
- alle controllers ok

**Comment by Badlapje** [comment]
- alle templates ok (nu dus nog mails)

**Comment by Badlapje** [comment]
ik ga de mails nog wat uitstellen tot die teksten zijn nagekeken door Ellen & de vrijwilligers

**Comment by Badlapje** [comment]
nieuw issue aangemaakt voor email
