### ISSUE TITLE
Search filters - allemaal implementeren

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#101]
alle filters uit de wireframe implementeren

**Comment by SnelleJelle** [comment]
@Badlapje Ik had graag hierover eens gebrainstormed.

**Comment by Badlapje** [comment]
alright, via mail afgesproken woensdag ;-)

**Comment by Badlapje** [comment]
alle filters buiten sector zijn ondertussen ok

**Comment by Badlapje** [comment]
qua sorteren: enkel sorteren op afstand mankeert nog voorlopig, maak ik een nieuwe issue voor aan

**Comment by Badlapje** [comment]
done, zit nu ook in #237
