### ISSUE TITLE
Organisation handle vacancies

### ISSUE THREAD

**Issue by SnelleJelle** [howest-wsde/VrijwilligersTool#108]
Ervoor zorgen dat beheerders voor een organisatie de mogelijkheid hebben om een kandidatuur voor een vacancy goed- of af te keuren.

**Comment by durnezj** [comment]
wat wordt bedoeld met handle? Het contacteren van de contactpersoon of het oplijsten van de kandidaten voor de vacatures van de user?

**Comment by SnelleJelle** [comment]
@durnezj het goedkeuren en afkeuren van een **kandidaatstelling** (candidacy)

**Comment by durnezj** [comment]
worden deze in het profiel weergegeven of in een aparte pagina?

**Comment by beuntje** [comment]
mag in de pagina van de vacancy zelf, onderaan bv. een overzicht van de personen die ingeschreven zijn met een link naar al dan niet goedkeuren. 
Voorlopig hoef je je ook niet veel aan te trekken van al dan niet het recht om de pagina aan te passen. In de branch "dev-vrijwilligervinden" ben ik bezig verschillende beheerders te maken voor organisaties. Deze kunnen we daar dan achteraf aan koppelen. (voorlopig mag je dus gewoon laten dat iedereen die de vacature ziet ook kan goedkeuren en afkeuren)

**Comment by durnezj** [comment]
@Badlapje 
Ik heb dit nu voorlopig op deze manier gedaan en heb geredeneerd dat een gebruiker naar zijn profiel kan gaan en daar zn organisaties beheert met de vacatures en de kandidaatstellingen.
In de mockups stond dit zo, maar ik zal het wat aanpassen naar de comment hierboven van @beuntje .

**Comment by wsde** [comment]
Neen, laat maar staan zoals staat in de mockups, we kunnen dit later eventueel aanpassen afhankelijk van de design. Nu is het vooral belangrijk dat het werkt. 
(Beuntje, via account op gsm)

**Comment by Badlapje** [comment]
@durnezj begrijp ik dan goed dat je hier voorlopig mee klaar bent zoals in de mockups?  Zo ja: maak je dan een pull request?

**Comment by durnezj** [comment]
@Badlapje Ik ben hier voorlopig aan bezig, nu ben de pagina aan het maken voor het approven van de candidacies.

**Comment by durnezj** [comment]
@Badlapje ik heb een pull request aangemaakt voor deze: https://github.com/howest-wsde/VrijwilligersTool/pull/139

**Comment by beuntje** [comment]
Verdere aanpassingen en optimalisaties overgenomen en ingevoerd in dev-kandidaturen
