### ISSUE TITLE
edit existing vacancy

### ISSUE THREAD

**Issue by SnelleJelle** [howest-wsde/VrijwilligersTool#109]
Allow for organisation to edit only their vacancies.

**Comment by MKoen** [comment]
@SnelleJelle  hier zou ik aan werken. Dus het punt ervan is dat ik een pagina aanmaak, voor gebruikers die creator zijn van een organisatie, waarin al de vacancies van die organisatie(s) van die gebruiker opkomen waar hij/zij die kan aanpassen?

**Comment by SnelleJelle** [comment]
@MKoen correct!

**Comment by Badlapje** [comment]
check zeker de wireframes ;-)

**Comment by MKoen** [comment]
@SnelleJelle De basis ervan werkt nu en de db wordt geupdate. Maar ik neem aan dat de startdate niet mag/moet aangepast worden sinds dat dat de datum is wanneer de vacature is aangemaakt? (Anders, als de datum voor vandaag valt komt er en validity warning dat de datum voor vandaag valt)

**Comment by SnelleJelle** [comment]
@MKoen goed opgemerkt! Een datum aangepast worden, maar enkel naar een datum die later valt dan _vandaag_. Ook mag een vacature maximum 6 maandag duren.

**Comment by MKoen** [comment]
@SnelleJelle Ok, maar als de gebruiker het wil aanpassen op een datum na de startdatum, is de gebruiker dan verplicht om de startdatum te veranderen naar minstens _vandaag_?

**Comment by SnelleJelle** [comment]
@MKoen ja, denk ik.

@beuntje @Badlapje

**Comment by MKoen** [comment]
@SnelleJelle  moet de gebruiker op de edit pagina blijven als hij op _Opslaan_ heeft geklikt of moet deze terug naar de pagina verwezen worden met informatie over die vacature?

**Comment by beuntje** [comment]
startdatum aanpassen: hoeft niet perse gedwongen te worden naar datum van minstens vandaag; als de gebruiker een reden heeft dit aan te passen naar een datum in het verleden moeten wij dit niet weigeren. 

na opslaan: terug naar effectieve vacature-pagina (info over de vacature), anders kan er verwarring zijn over of het al dan niet opgeslaan is.

**Comment by MKoen** [comment]
@beuntje moet ik de validatie van de server dan overrriden zodat data voor _vandaag_ toegestaan zijn?

**Comment by beuntje** [comment]
startdatum mag je weglaten uit de user input. In de database moet deze bewaard blijven als referentie van wanneer de vacature ingegeven is, maar voor de gebruiker heeft deze datum eigenlijk geen meerwaarde. (bij het tonen van de vacature kan deze ook getoond worden als "datum aanmaak vacature")

**Comment by MKoen** [comment]
@beuntje ok, komt in orde

**Comment by MKoen** [comment]
@beuntje Nu kan men niet meer de startdate aanpassen, bij het creëren van een nieuwe vacature kan men ook niet zelf de startdate (dus de datum van aanmaak) aanpassen maar is deze standaard de 'vandaag'-dag

**Comment by beuntje** [comment]
voorlopig hoef je je ook niet veel aan te trekken van al dan niet het recht om de pagina aan te passen. In de branch "dev-vrijwilligervinden" ben ik bezig verschillende beheerders te maken voor organisaties. Deze kunnen we daar dan achteraf aan koppelen.

**Comment by MKoen** [comment]
@beuntje Okido, op dit moment staat er dus aan de onderkant van een vacature een link naar de pagina om die vacature aan te passen, en als men op _Opslaan_ klikt wordt met teruggestuurd naar de vacature zelf. Alles behalve de startdate kan dus aangepast worden van een vacature.

**Comment by MKoen** [comment]
@beuntje @SnelleJelle ik zat er gisterenavond nog wat aan te denken en er kwam me een klein ideetje te binnen geschoten.
Zou het handig zijn moest een vacature een extra property krijgen zoals bvb. 'lastEditDate', dat er zo wordt bijgehouden wanneer de vacature voor de laatste keer is aangepast? Het zou misschien ook handig zijn dat de edit vacancy page dan ook een _Cancel_ button heeft, als men dan op die pagina zit, maar toch niets wil aanpassen, men gewoon het kan annuleren? Misschien dat er bij de vacature dan in kleine lettertjes ofzo kan bijstaan wanneer het voor het laatst is aangepast?

A good or not so good idea?

**Comment by beuntje** [comment]
Hoeft er niet bij wat mij betreft.

**Comment by MKoen** [comment]
Ok

**Comment by Badlapje** [comment]
die cancel button lijkt mij wel een goed idee, (niet die lastEditDate)... gebruikers moeten altijd de mogelijkheid hebben om op hun stappen terug te keren, en niet alle gebruikers kennen de back-button in de browser of zullen dan op één van de linken in de pagina drukken om bv. naar de homepage of zo te gaan.

**Comment by MKoen** [comment]
@Badlapje Oke, zal die cancel button toevoegen en pull request maken
