### ISSUE TITLE
Telefoonnummer-validatie

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#112]
template:
- [x] placeholders invullen met verwachte notatie: bv. "0123 456789"

function validateTelephone : 
- [x] geen `$telephone = str_replace(' ', '', $org->getTelephone());` maar 1.) geen replacement of 2.) alle niet-numerieke karakters replacen (bv. "/")
- [x] aantal karakters flexibeler laten: gsm heeft 10 numerieke karakters, vast nummer 9 karakters, incl. landsnummer = 10/11, maar met "+"-teken voor
- [x] ook bv. (+32)486/69.14.57 toelaten en interpreteren

**Comment by Badlapje** [comment]
hm, items 2-4 zouden moeten ok zijn, maar krijg momenteel volgende foutmelding wanneer ik een persoon probeer aan te maken:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.urlid' in 'field list'") in base.html.twig at line 75.

working on that

**Comment by Badlapje** [comment]
en yup: ik heb de dbase gedropped en dan gerebuild om zeker te zijn...

**Comment by Badlapje** [comment]
opgelost :-)  Nu nog ES terug online krijgen en 't is in de sjakosj :dancer:
