### ISSUE TITLE
"recente verenigingen" in plaats van "recente vrijwilligers" 

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#114]
verenigingen moeten meer zichtbaar geplaatst worden dan individuen

**Comment by SnelleJelle** [comment]
@MKoen Als je meebent met csrf mag je hieraan beginnen.

(dit heeft niet direct iets te maken met csrf, maar @Badlapje vond deze opdracht geschikter dan wat ik voor jou in petto had :p )

**Comment by MKoen** [comment]
@SnelleJelle Kheb de recente vrijwilligers vervangen door de recente verenigingen. Dit staat op dev-recent-organisations

**Comment by Badlapje** [comment]
@MKoen kan je een pull request maken zodat ik kan mergen?

**Comment by SnelleJelle** [comment]
@MKoen zie  (kleine) commentaar

**Comment by MKoen** [comment]
@SnelleJelle  heb het toegepast
