### ISSUE TITLE
telefoonnummervalidatie voor vereniging 

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#116]
- [x] De foutmelding zegt "telefoonnummer is reeds in gebruik" (ofzo) bij reeds bestaande e-mail
- [x] sidenote: Waarom zou een e-mailadres van een vereniging uniek moeten zijn? Ik kan als persoon met 1 e-mailadres toch verantwoordelijk zijn voor verschillende verenigingen? Idem voor telefoonnummer
- [x] telefoonnummer: bij het ingeven van een langer telefoonnummer krijg ik geen validatie-fout, maar wel foutmelding dat de lengte van het DB-veld overschreden wordt
- [x] gewone string (zoals bv. "blah") bij telefoonnummer geeft een notNumericException bij zowel vereniging als persoon

**Comment by Badlapje** [comment]
denk dat 3 moet opgelost zijn, ik kijk hier morgen eens voor om zeker te zijn.  1 en 2 zouden simpel moeten zijn, kijk ik ook voor.

**Comment by Badlapje** [comment]
unique restraint weggehaald voor telefoonnummer en email bij vereniging.  Is inderdaad niet logisch in het kader van feitelijke verenigingen.

**Comment by Badlapje** [comment]
extra foutje gevonden en gefixed

**Comment by Badlapje** [comment]
#159
