### ISSUE TITLE
zoekopdrachten deelbaar maken

### ISSUE THREAD

**Issue by SnelleJelle** [howest-wsde/VrijwilligersTool#120]
- Op de zoekpagina moet een knop komen "**deel zoekopdracht**"
- Op het zoekformulier moet **csrf** terug geënabled worden
- Een **gedeelde zoekopdracht** die bekeken wordt mag **niet opgeslagen** worden
- Enkel een zoekopdracht die uitgevoerd wordt _door het sumbitten van het formulier_ mag **opgeslagen** worden

**Comment by SnelleJelle** [comment]
- Op de zoekpagina moet een knop komen "deel zoekopdracht"
 - Op het zoekformulier moet csrf terug geënabled worden
 - Een gedeelde zoekopdracht die bekeken wordt mag niet opgeslagen worden
 - Enkel een zoekopdracht die de user zelf heeft opgegeven mag opgeslagen worden

**Comment by SnelleJelle** [comment]
Continue from branch https://github.com/howest-wsde/VrijwilligersTool/tree/dev-saving-searchFilters

**Comment by MKoen** [comment]
@SnelleJelle Database & Elastica upgedate, ben nu eens aan het kijken hoe alles nu juist al werkt

**Comment by MKoen** [comment]
@SnelleJelle  In de db is term not nullable, maar de zoekterm is optioneel. Mag/moet de term wel nullable worden of mag de term niet meer optioneel zijn?

**Comment by SnelleJelle** [comment]
@MKoen je mag de term nullable maken!
goede opmerking!

**Comment by MKoen** [comment]
@SnelleJelle  Zou het een goeie manier zijn om $_SERVER['HTTP_REFERER'] in een sessie variabele te steken en dan kijken van waar deze komt? Als deze dan niet van de zoekpagina zelf komt, zal deze niet in de database gestoken worden.
(Btw, 'term' al nullable gemaakt)

**Comment by SnelleJelle** [comment]
HTTP_REFERER is ook een goede oplossing.
Ideal zou zijn als je niet "localhost" gebruikt maar de dns-naam van de server (dynamisch)

**Comment by MKoen** [comment]
@SnelleJelle  Ja dat bedoelde ik met dat het een var is, het is niet statief "localhost" maar m.b.v. $_SERVER['REQUEST_URI']  :)

**Comment by MKoen** [comment]
@SnelleJelle  Nog een vraagje voor de knop voor het te delen, wat moet dat juist doen? De url in de user zijn clipboard steken?

**Comment by SnelleJelle** [comment]
@MKoen een url genereren (waar door iedereen naartoe kan genavigeerd worden) die de zoekfilters instelt en toepast zoals die ingesteld zijn op de het formulier vanwaar de zoekopdracht gedeeld wordt.

Om dit visueel voor te stellen:

1.  user stelt filters in
2.  user submit formulier
3.  user ziet resultaten
4.  user klikt op "delen"
5.  pagina wordt  greyed-out en er komt een popup tevoorschijn
6. in die popup staat de url
7. onder de url staan opties voor delen op sociale media
8. een lijntje tekst dat zegt "zoekopdracht is naar het klembord gekopiëerd"
9. een sluitknop met een kruis icoontje bovenaan rechts aan de popup

**Comment by MKoen** [comment]
Nu is er een knop op het te delen, indien de user erop klikt komt er een popup met de url en knopjes om het te delen op fb, twitter, g+ en linkedin. Ook een knop om de url op hun klembord te zetten. Onderaan ook een knopje om de popup te sluiten. Zal nu kijken om de code op te kuisen.

De popup ziet er zo uit:
![search_share](https://cloud.githubusercontent.com/assets/17765414/15425680/2aeff6fe-1e8a-11e6-8035-2c729dc238de.png)

**Comment by SnelleJelle** [comment]
@MKoen ziet er goed uit!

heb je csrf al toegepast op het forulier?

**Comment by MKoen** [comment]
@SnelleJelle Dat nog niet, maar zal daar voor kijken als code is opgekuist

**Comment by SnelleJelle** [comment]
@MKoen Ik vermeld het omdat je er waarschijnlek problemen mee zal ondervinden

**Comment by MKoen** [comment]
@SnelleJelle Ok, ik laat wel weten als ik er zal aan beginnen

**Comment by MKoen** [comment]
@SnelleJelle De code is nu wat opgekuist. Zal eens beginnen kijken voor de csrf

**Comment by MKoen** [comment]
@SnelleJelle  heb csrf aangezet, een een hidden input aan de zoekpagina toegevoegd met de csrf token in, en ik heb sinds de hidden input er staat geen errors gekregen. Moet ik de code anders eens pushen dat je het ook kan zien?

**Comment by SnelleJelle** [comment]
@MKoen ja

**Comment by MKoen** [comment]
@SnelleJelle  Ah nee, toch errors, khad  "csrf_protection" op true gezet, maar blijkbaar was dat terug naar false gekomen. Dusja nu krijg ik wel de error dat de token ongeldig is. Sorry voor het misverstandje

**Comment by MKoen** [comment]
@SnelleJelle Staat nu op true, en heb de _input_ voor die token vervangen met _{{ form_row(form._token) }}_ en krijg die error nu niet meer. Is dat de 'oplossing'?

**Comment by SnelleJelle** [comment]
@MKoen push eens?

**Comment by MKoen** [comment]
@SnelleJelle  is dat dus in orde? :stuck_out_tongue:

**Comment by SnelleJelle** [comment]
@MKoen heb er nog niet naar kunnen kijken sry

**Comment by MKoen** [comment]
@SnelleJelle Ah geen probleem :)

**Comment by SnelleJelle** [comment]
@MKoen de {{ form_row(form._token) }} hoef je niet mee te geven, dit gebeurt automatisch. Zelfs in de twig

**Comment by MKoen** [comment]
@SnelleJelle ah oke zal ik doen, moet er dan nog iets daarbij of is dat dan in orde?

**Comment by MKoen** [comment]
@SnelleJelle als ik dat weg doe krijg in een _No alive nodes found in your cluster_ error, is dat het probleem waar je het over had?

**Comment by MKoen** [comment]
@SnelleJelle Heb dat weggedaan, en het blijft werken. (ik krijg toch geen errors)
Zal het pushen

**Comment by Badlapje** [comment]
@MKoen hoe ver staat dit?  Is dit af en gemerged in de dev?

**Comment by MKoen** [comment]
@Badlapje  Voor zover ik weet werkt dat, maar wou nog niet mergen sinds het de branch van Jelle was, maar anders maak ik een pull request hiervoor nu

**Comment by Badlapje** [comment]
dikke merci, ga het tegen vanavond mergen dan :-)

**Comment by Badlapje** [comment]
deze functionaliteit moet nog gemerged worden in searchDev (gezien de hoop wijzigingen daar kan er hier ook werk aan de winkel zijn)

**Comment by Badlapje** [comment]
SearchFilter en SearchFilterType zijn geüpdate, nu nog js en zo integreren :-)

**Comment by Badlapje** [comment]
@MKoen mocht je tijd hebIben, kan je dan snel wat documentatie schrijven voor het delen van searches?  
Kwestie dat ik weet in welke files ik moet kijken en hoe je het in elkaar stak.  Als ik het goed doorheb, dan:
- moet ik in web/js/search.js kijken naar lijn 51 - 97?
- lijn 66 - 85 in app/Resources/views/search/zoekpagina.html.twig?
- de volledige searchfiltercontroller?
- app/resources/searchResult/searchFilter.html.twig?
- app/resources/views/search/history_search.html.twig?

Qua flow: 
  bij renderen zoekblok met geschiedenis geef je via recentsearchfiltersaction de 5 recentste searchfilters weer (niet deelbaar als ik het goed voorheb)?
  bij renderen volledige zoekpagina staat er onder de zoekopdracht (fin, onder de filters), een button "zoekopdracht delen".  Als je daarop klikt dan opent er een popup en wordt de url van de huidige pagina in #search_url gezet, en dan kunnen de gebruikers kiezen om die te kopiëren.

Is er nog iets wat ik vergeet?

**Comment by MKoen** [comment]
@Badlapje ik zal er zeker eens voor kijken

**Comment by MKoen** [comment]
@Badlapje [Korte documentatie](https://github.com/howest-wsde/VrijwilligersTool/files/410629/DocSearchSharing.txt) gemaakt.

Moest je nog vragen hebben, of moest ik iets te weinig (of verkeerd) geformuleerd hebben, laat zeker iets weten. Ik help jullie met plezier.

**Comment by Badlapje** [comment]
@MKoen Dikke merci!

**Comment by MKoen** [comment]
@Badlapje Graag gedaan :)
