### ISSUE TITLE
Detailpagina vereniging

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#123]
Deze is nu veel te basic. Het plannetje van uit de vacatures kan overgenomen worden, en onder de vereniging mag een oplijsting van hun vacatures.

**Comment by SnelleJelle** [comment]
https://github.com/howest-wsde/VrijwilligersTool/tree/dev-detail-org

**Comment by SnelleJelle** [comment]
vacatures worden opgelijst

**Comment by SnelleJelle** [comment]
google maps toegevoegd

**Comment by SnelleJelle** [comment]
#140
