### ISSUE TITLE
Voorlopige homepage

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#124]
- [x] 6 laatste nieuwe vacatures
- [x] 3 laatste nieuwe organisaties

**Comment by Badlapje** [comment]
alright, met deze begin ik na de middagpauze :-)

**Comment by Badlapje** [comment]
6 laatste nieuwe vacatures zijn gedaan.  Heb hiervoor de listRecentVacanciesAction voor hergebruikt en uitgebreid met een viewmode option.  Idem voor de recente_vacatures.html.twig file.

**Comment by Badlapje** [comment]
@beuntje je zet daar voor ingelogde gebruikers andere zaken: klopt dat?  Op de wireframes staat dat niet, maar mss komt dat van op de klankbordmomenten?

**Comment by beuntje** [comment]
de verenigingen moesten meer zichtbaar komen dan de ingeschreven vrijwilligers

**Comment by Badlapje** [comment]
yup, maar dat bedoel ik niet.  Misschien lees ik het verkeerd, maar hierboven zeg je dat voor ingelogde gebruikers op de homepage de blokken 6 laatste nieuwe vacatures en 3 laatste nieuwe organisaties vervangen moeten worden door liked organisaties/vacatures en eigen organisaties/vacatures.

**Comment by beuntje** [comment]
ach, ok, dat zijn enkele blokken die volgens mij toch zowieso ergens moeten komen... dus had ik dat in de issues gezet onder de homepage om daar voorlopig al iets van invulling te hebben.

**Comment by Badlapje** [comment]
oki, dan ga ik dat in een aparte issue zetten, kwestie dat het los staat van de homepage (kan ik dan doen nadat ik alle issues voor de homepage heb opgelost, net op een pak zaken gelopen die nog moeten aangepast worden)
