### ISSUE TITLE
Sharing for facebook

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#14]

**Comment by Badlapje** [comment]
@MKoen hoe staat het hier mee?

**Comment by MKoen** [comment]
Ik ben op dit moment bezig met het registeren via social media. Maar voor zover ik weet had Robin mij gezegd dat hij ging kijken voor het "sharing for facebook".

**Comment by beuntje** [comment]
Zijn er problemen met het inloggen via social media? Als er dingen zijn waar je niet direct een oplossing oor vindt, stel je best vragen voor je vast loopt...

**Comment by MKoen** [comment]
Ik heb een paar dagen geleden een mailtje naar je gestuurd i.v.m. social media, heb je deze niet gekregen misschien? 

Moest je deze niet gekregen hebben, mijn vraag is de volgende:

In "login.php" staat er vanboven "include("inc.config.php");" maar dat bestand heb ik niet staan.
Hiermee krijg ik een error dat het de variabele "cfgMain" niet kent. Ligt dat daaraan?

**Comment by beuntje** [comment]
ja, ik had de mail idd nog niet gezien, sorry hiervoor. (ondertussen heb ik een autoforwarder ingesteld van m'n howest-mail naar m'n persoonlijke mail zodat ik sneller kan opvolgen). 

de inc.config.php bevatte bij mij enkel een aantal parameters zoals database-connectie en facebook-app-ID of facebook secret key. Deze kun je dus op de symfony-way invullen in de code.

**Comment by MKoen** [comment]
Juist gezien dat Google blijkbaar niet meer OpenID 2.0 ondersteund. (https://developers.google.com/identity/protocols/OpenID2Migration)
Ik zal eens kijken voor eventueel een alternatief hiervoor.

**Comment by MKoen** [comment]
Het sharen (en liken) via facebook moeten normaal gezien werken, ik zal dit pushen op mn branch wanneer ik ook klaar ben met sharen via linkedin. Ook heb ik de inhoud van de mails ietsje beter gemaakt.

**Comment by MKoen** [comment]
Het is gecommit op mijn branch

**Comment by Badlapje** [comment]
kan je een pull request maken om het te mergen in de dev branch?  Dan kijk ik na en kan het gemerged worden ;-)

**Comment by Badlapje** [comment]
Koen, ik krijg exceptions als ik jouw branch uitcheck en probeer te runnen.  Heb jij al een schema update gedaan van je dbase en de laatste dummy data geïmporteerd?

**Comment by MKoen** [comment]
@Badlapje Ah nog niet gedaan, zal dat direct doen en pushen

**Comment by MKoen** [comment]
@Badlapje  hmmm, de entities in mijn branch zijn wel die van een paar weken geleden, dus als ik de database aanmaak via doctrine dan maakt het niet, onderandere, de person table aan. Moet ik dan de entities van de dev branch in mijn branch steken?

**Comment by SnelleJelle** [comment]
@MKoen Ja, de meest propere manier om dit te doen is door de **dev** branch te mergen in de **dev_KM** branch.

**Comment by MKoen** [comment]
@SnelleJelle Ok, merci, al daar voor kijken

**Comment by Badlapje** [comment]
wat Jelle zegt.  Je moet eigenlijk regelmatig tijdens het ontwikkelen de dev branch eens mergen in je development branch zodat je zeker bent dat je op de recentste versie werkt.

**Comment by MKoen** [comment]
@Badlapje Ik heb dev_KM gemerged met dev, normaal gezien zou de db in orde moeten zijn. Ik zal een nieuwe pull request maken

**Comment by SnelleJelle** [comment]
@Badlapje closen?
