### ISSUE TITLE
create reusable search block

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#154]
can be adaptation of what is currently in base.html.twig
- [x] create twig template for basic search block (header)
- [x] create twig template for non-basic search block (eg. profile page, vrijwilliger worden, ... )
- [x] adapt base, index and any other template where a search block is needed
- [x] alle placeholders en labels importeren uit validation.nl.yml/eng.yml => werkt niet om één of andere reden in de Controller (use statement)

**Comment by Badlapje** [comment]
onderscheid gemaakt in twee aparte forms, ééntje voor de basic header form (plain 'n simple) en ééntje voor de andere pagina's met uitgebreidere functionaliteit.

**Comment by Badlapje** [comment]
@SnelleJelle De branch dev-saving-search-filters ... in hoeverre is die klaar?  Ik heb nu de reusable templates aangemaakt, zou graag de bewaarde zoekopdrachten en recente zoekopdrachten ook erin steken, maar moet ff weten in hoeverre ik van nul begin of in hoeverre ik verder ga/importeer van die branch?

**Comment by SnelleJelle** [comment]
@Badlapje het opslaan werkt normaal gezien, maar er moest nog een oplossing gezocht worden om zoekopdrachten _op te slaan_ en te _sharen via de url_ **en** _CSRF protection_ te behouden.

PS: ik zie niet alles passeren, af en toe kom ik eens kijken hoe het vlot.
Als je mij nodig hebt wil ik gerust eens een dag afkomen of vraag het mij via mail.

**Comment by Badlapje** [comment]
alright, zal donderdag/vrijdag eens kijken en een seintje geven :smile:

**Comment by Badlapje** [comment]
Voor de afwerking, zie issue #82 => licht aangepast om de twee functionaliteiten er in te zetten, #83 was eigenlijk dubbel
