### ISSUE TITLE
Sharing for LinkedIn

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#16]

**Comment by Badlapje** [comment]
Koen, hoe staat het hier mee?

**Comment by MKoen** [comment]
Ik ben op dit moment bezig met het registeren via social media. Maar voor zover ik weet had Robin mij gezegd dat hij ging kijken voor het "sharing for LinkedIn".

**Comment by MKoen** [comment]
Het is gecommit op mijn branch

**Comment by SnelleJelle** [comment]
@Badlapje @beuntje closen?

**Comment by beuntje** [comment]
neen, ik zie "delen via linkedin" nog niet staan op de dev

**Comment by SnelleJelle** [comment]
@MKoen ?

**Comment by MKoen** [comment]
@SnelleJelle dat is blijkbaar weg in vacature.html.twig ? Maar in sharebuttons.js staat nog de code die de link voor het delen via linkedin een data-url geeft. Zal eens kijken of er daar geen commits ofzo meer van zijn

**Comment by MKoen** [comment]
@SnelleJelle @beuntje dus de div ervan was weg in vacature.html.twig samen met de script src van platform.linkedin.com. Nu heb ik dat opgelost, mag ik dit pushen op de dev branch?

**Comment by beuntje** [comment]
in een aparte branch pushen en merge request aanmaken

**Comment by beuntje** [comment]
Als ik een vacature probeer te delen via de linkedin-knop (http://dev.roeselarevrijwilligt.be/vacature/Barmedewerker), krijg ik een link naar de root van de site. Van de andere social platforms is dit wel de correcte pagina...

**Comment by MKoen** [comment]
@beuntje zal dat fixen

**Comment by MKoen** [comment]
@beuntje  Zou nu normaal moeten werken, ik heb het getest en kreeg de juiste link

**Comment by beuntje** [comment]
ik zie dat je idd de juiste URL doorgeeft. Ik vind de URL die linkedIn previewt wat vreemd eruit zien, maar da's misschien omdat we de OG-tags nog niet instelden. 
Is OK
