### ISSUE TITLE
Logica vacatures op maat maken

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#163]
matching gebeurt in ES:
- [x] Open vacancies: filter
- [x] startDate?  Hoe dichter hoe beter? (idee dat vacatures die lang open staan mss minder interessant zijn ... zeer kleine negatieve impact via sliding scale, p309)
- [x] indien locatie: nabijheid (sliding scale, p309)
- [x] per skill in vacature die matcht aan skill vrijwilliger: boost
- [x] accessibility to weelchair/mindervaliden ifv nood vrijwilliger (enkel indien die nood er is): filter
  - [x] veld aanmaken bij persoon
  - [x] veld mappen in ES
  - [x] veld toevoegen aan persoonlijke voorkeuren die kunnen ingesteld worden
- [x] Verloning: filter indien wens van de vrijwilliger
  - [x] veld aanmaken bij persoon
  - [x] veld mappen in ES
  - [x] veld toevoegen aan persoonlijke voorkeuren die kunnen ingesteld worden
- [x] Longterm: filter afhankelijk van de wensen van de vrijwilliger
  - [x] veld aanmaken bij persoon
  - [x] veld mappen in ES
  - [x] veld toevoegen aan persoonlijke voorkeuren die kunnen ingesteld worden
- [x] Estimated work in hours: sliding scale afhankelijk van de wensen van de vrijwilliger
  - [x] veld aanmaken bij persoon
  - [x] veld mappen in ES
  - [x] veld toevoegen aan persoonlijke voorkeuren die kunnen ingesteld worden
- NIET WEERHOUDEN Verloning: bonus indien aanwezig
- [x] Sociale interactie: bonus afhankelijk van de wens van de vrijwilliger
  - [x] veld aanmaken bij persoon
  - [x] veld mappen in ES
  - [x] veld toevoegen aan persoonlijke voorkeuren die kunnen ingesteld worden
- [x] Indien in de bewaarde organisaties van de vrijwilliger: boost
  - [x] methode aanmaken bij persoon om alle id's te krijgen van "liked" organisations
- [x] Ev. afhankelijk van het aantal likers voor die vacature? (sliding scale)
  - [x] methode aanmaken bij vacature
  - [x] veld mappen in ES
- [x] bring it all together in vacancyController

**Comment by Badlapje** [comment]
@beuntje heb hier een aantal factoren opgesomd die volgens mij invloed moeten hebben op hoe relevant een vacature is voor een gebruiker.  Kijk jij eens na.  Dit zijn allemaal zaken die een bonus/malus geven of een filter zijn op de vacancies (zodat alles wat niet voldoet weg is).  Bij sliding scale is de bonus/malus niet constant.  Bv. bij afstand zal hoe verder weg hoe slechter zijn, bij beloning hoe hoger hoe beter.

**Comment by beuntje** [comment]
ik zou de "Verloning: bonus indien aanwezig" weglaten, de filter indien wens van de gebruiker moet er wel blijven

misschien ook nog boost voor vacature waar meerdere vrijwilligers gezocht worden

**Comment by Badlapje** [comment]
eventueel een boost als de organisatie van de vacature meerdere testimonials heeft (duid op een toffe werkomgeving)

**Comment by beuntje** [comment]
kan idd ook erbij, we moeten dan wel ergens vermelden hoe ze kunnen zorgen dat hun vacatures beter scoren
