### ISSUE TITLE
implement adaptive placeholders

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#165]
[zie punt 2](http://usabilitygeek.com/5-registration-form-usability-guidelines/)

**Comment by beuntje** [comment]
het twitter-concept "e-mail or telephone number" vind ik ook wel goed

**Comment by Badlapje** [comment]
yup, en perfect te combineren.  Iets soortgelijks als dat van twitter hebben we al dacht ik he?
