### ISSUE TITLE
Google Maps - Vacancy

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#17]
Implement google maps functionality for vacancies:

- show vacancy on a map
- get distance from user to vacancy and use it to populate the views with (full, preview, ... )
- add possiblity to get a route description from user to vacancy via google maps & relevant views

**Comment by durnezj** [comment]
This has been implemented together with the Google Maps - User issue.
Will not close this yet, maybe someone needs to review this.

**Comment by Badlapje** [comment]
which branch is this on?  Can you create a pull request so i can review and close?

**Comment by durnezj** [comment]
fixing the map not loading and adding icons/labels

**Comment by SnelleJelle** [comment]
This feature works for me. Just the route description should be hidden.
@durnezj

**Comment by Badlapje** [comment]
ik zie precies wel dat er telkens 2 bubbles staan?  Pas zichtbaar als je inzoomt wel, 1 standaard en 1 custom

**Comment by durnezj** [comment]
@Badlapje is dit op je lokale versie of op dev.roeselarevrijwilligt.be?
op de release kan ik hem niet meer updaten de website.

**Comment by durnezj** [comment]
@SnelleJelle 
the route description has now been hidden by default: 9958599994f6e2395424c172822548c75d87393a

**Comment by Badlapje** [comment]
dat was op mijn lokale machine (fin, die van @SnelleJelle )

**Comment by durnezj** [comment]
Is deze dan in orde?

**Comment by Badlapje** [comment]
had jij hiervoor al een pull request aangemaakt Thibault?

**Comment by SnelleJelle** [comment]
@Badlapje @beuntje closen?

**Comment by beuntje** [comment]
Behalve het zoomlevel ziet dat er ok uit. 
Zou het mogelijk zijn standaard iets minder uit te zoomen, en als er geen exact adres is voor de vereniging zou de marker best niet geplaatst worden, maar een algemene zoom op de ingegeven stad / gemeente. 
Nog niet closen dus

**Comment by SnelleJelle** [comment]
@durnezj ^

**Comment by durnezj** [comment]
@beuntje @SnelleJelle ok, zal ik nog even herwerken.

**Comment by durnezj** [comment]
@beuntje wat bedoel je met minder uitzoomen, het staat nu namenlijk op de kleinst mogelijke zoom om de plaats van de vacature en de user allebei te tonen en de weg ertussen.

**Comment by beuntje** [comment]
Als er geen weg te berekenen valt (bv. niet ingelogd) staat er veel te hard ingezoomd

**Comment by durnezj** [comment]
@beuntje ik heb alles terug gefixt en grondig getest en de gevraagde changes voor google maps werden geimplementeerd.
