### ISSUE TITLE
Vacancy: finish it

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#178]
- [x] Er voor zorgen dat bij het tonen van vacancies, standaard enkel die getoond worden die én gepubliceerd én niet ingevuld zijn.
- [x] ES aanpassen zodat die ook het dbase schema volgt
- [x] kijken of adres moet geoptimaliseerd worden => question tbd met Benedikt
- [x] blokken aanpassen/aanmaken die vacatures tonen
      - [x] bewaarde vacatures
      - [x] recente vacatures
      - [x] verwijderde vacatures
- [x] listparentskillsaction verhuizen naar een skillcontroller
- [x] vacature verwijderen
   - [x] controller voorzien => changeVacancyPublishedStatusAction
   - [x] render in template for tile view
   - [x] render in template for full view
- [x] vacature herstellen mogelijk maken
- [x] beveiliging backend voor edit actions
- [x] other stuff that pops up...

**Comment by Badlapje** [comment]
Voorlopig omwille van verminderen aantal dbase queries wordt adres niet geoptimaliseerd.

**Comment by Badlapje** [comment]
voorlopig adres niet refactoren in eigen entity: zou enkel voor een hoop join-queries zorgen, niet nodig op dit moment

**Comment by Badlapje** [comment]
@beuntje Betekent een vacature liken dat je die bewaard?

**Comment by beuntje** [comment]
yeps, is in je favorieten plaatsen. Heb er nog geen geschikte eenduidige naam voor :-)
(in de layout is het dat sterretje)

**Comment by Badlapje** [comment]
alright, heb dat veranderd naar bewaar/ontwaar, kwestie van duidelijkheid wat het is (fin, de tekst wel te verstaan, niet de klasse-namen)

**Comment by Badlapje** [comment]
@beuntje heb op vacancyDev de mogelijkheid toegevoegd om een vacature te verwijderen en er ook voor gezorgd dat in de tile view van een vacancy er een link wordt gerenderd "delete" als de user ook een admin is.  

Kijk jij om daar een ajax request van te maken en er een icoontje voor te gebruiken?

**Comment by Badlapje** [comment]
ajaxify en icon toegevoegd in #147 zodat deze issue kan gesloten worden
