### ISSUE TITLE
Opkuis vereniging

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#184]
- [x] vereniging.html.twig aanpassen
- [x] vereniging_min.html.twig aanpassen
- [x] mogelijkheid tot deleten
- [x] mogelijkheid tot herstellen
- [x] mogelijkheid maken een vereniging aan te passen eens ze gemaakt is
- [x] sectoren toevoegen
- [x] #150 
- [x] #151 
- [x] listorganisationvacancies aanpassen zodat enkel het aantal openstaande vacatures wordt weergegeven in vereniging_min.html.twig
- [x] vacature types aanpassen zodat sectoren er niet bij komen
- [x] lijst in footer aanpassen zodat sectoren er niet bij komen
- [x] admin toevoegen opnieuw laten werken

**Comment by Badlapje** [comment]
vereniging aanpassen is nu mogelijk (zit in pull request #192)

**Comment by Badlapje** [comment]
vereniging_min.html.twig roept nu de juiste (nieuwe) controller aan om het aantal openstaande vacatures weer te geven => zit in pull request #192

**Comment by Badlapje** [comment]
oplossing voor #151 gecommit

**Comment by Badlapje** [comment]
admin toevoegen werkte niet heb ik gemerkt, is nu gefixed met ipv. een tekstvak waar je de id van de persoon in kwestie moest invullen (met placeholder die zei email of username), gewoon een dropdown met alle gebruikers die een username hebben.

**Comment by Badlapje** [comment]
@beuntje om een organisatie te deleten: deleten we ze permanent of houden we ze in de dbase?  Indien het laatste:
- met een veld in organisation
- verhuis naar een andere tabel?

**Comment by beuntje** [comment]
ik zou kiezen voor een extra veld + delete uit elastic
