### ISSUE TITLE
Aanmaken van nieuwe account: username

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#191]
Als je enkel de eerste fieldset invult krijg je een SQL-foutmelding "Column 'username' cannot be null" . . 
> dit veld dus automatisch invullen als er geen ingevuld staat.

**Comment by Badlapje** [comment]
zie #192

**Comment by beuntje** [comment]
Als ik enkel de eerste stap doorloop binnen het aanmaken van een nieuwe account, dan blijft deze op NULL

**Comment by Badlapje** [comment]
Net geprobeerd en lukt perfect om een nieuwe account aan te maken nu?

De username blijft idd op nul, aangezien de gebruiker er geen invulde.  Is er een reden waarom die zou moeten ingevuld worden?  Zo ja, dan lijkt me dat een nieuwe issue?

**Comment by beuntje** [comment]
Ja, indien null krijg je bv fout als je naar 'mijn profiel' gaat (username
is nodig voor url)

Op 24 aug. 2016 23:22 schreef "Koen Cornelis" <notifications@github.com>:

**Comment by Badlapje** [comment]
't was wslijk beter geweest om een id te gebruiken, kwestie dat zo'n route toch niet semantisch moet zijn (niet belangrijk voor SEO).

Heb het opgelost door bij edit/creatie van een persoon te kijken of de username leeg is en zo ja: de username expliciet te zetten naar "gebruiker" + id.  Zit in PR #262
