### ISSUE TITLE
Weergave map bij organisatie / vacature werkt niet in IE

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#207]
ruimte wordt wel ingenomen maar blijft leeg.

getest op laptops stad Roeselare

**Comment by Badlapje** [comment]
is blijkbaar een probleem met flexbox, je kan het [hiermee oplossen](https://github.com/jonathantneal/flexibility)

zie ook [deze guide](https://css-tricks.com/using-flexbox/)

**Comment by Badlapje** [comment]
is al verbeterd in IE10, maar nog niet volledig opgelost.  De kaart is nog niet zichtbaar, en er zijn nog rare scrollbars edm.
![homepage](https://cloud.githubusercontent.com/assets/4058016/18162382/78dfdb4c-7036-11e6-89d2-3470a5cd5ccc.jpg)
![pagina organisatie](https://cloud.githubusercontent.com/assets/4058016/18162386/7f031264-7036-11e6-88ea-a088313f4ab4.jpg)

**Comment by Badlapje** [comment]
screenshots zijn van de homepage en een organisatiepagina

**Comment by beuntje** [comment]
Met welke browser werkte jij ook alweer?  Mijn MS Edge wil blijkbaar niet opstarten :-/

**Comment by Badlapje** [comment]
IE 10 en 11 voor die screenshots

**Comment by Badlapje** [comment]
@beuntje ik zie dat de kaart nog niet goed geladen wordt, de rest is ok :-)
