### ISSUE TITLE
Mogelijkheid geven om wachzin te tonen

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#208]
feedback testmoment 24/6
eventueel ook mogelijkheid om wachtzin te kopiëren naar klembord?

**Comment by durnezj** [comment]
Juist even deze geimplementeerd, maar ik zie het nut niet in van een wachtwoord te kunnen kopiëren naar het klembord. Dit zal volgend mij meer miserie voortbrengen ( compatibility issues voor alle browsers bij implementeren en security risico's) dan het nuttig is? :-)

**Comment by durnezj** [comment]
https://github.com/howest-wsde/VrijwilligersTool/pull/395

**Comment by Badlapje** [comment]
wachtwoord kopiëren was maar een ideetje, niet doen dan zou ik zeggen ;-)
