### ISSUE TITLE
Feedbackformulier blokkeert ingave op mobile

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#209]
- [x] Op een gsm blokkeert het feedbackformulier het toetsenbord blijkbaar telkens je iets wil ingeven (of feedback wil ingeven)

getest op 24/6

- [x] nazien feedback mogelijk maken op de release

**Comment by beuntje** [comment]
bootstrap feedback-form ingevoegd

**Comment by Badlapje** [comment]
gedaan en gemerged door benedikt vandaag
