### ISSUE TITLE
Foutmelding wanneer zoekpagina form gesubmit wordt zonder value

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#224]
app_dev.php/zoeken?q=  (gewoon klikken op de search-button in header zonder value in te vullen) geeft volgende foutmelding: "Error: Call to a member function isSubmitted() on null "

(line 314 in searchcontroller: "else if ($form->isSubmitted() && $form->isValid()) " )

**Comment by Badlapje** [comment]
duplicaat van #193
