### ISSUE TITLE
Organisatie - beheerders toevoegen dropdown

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#230]
- [ ] er moet een input met autocomplete bijkomen zodat de gebruiker de keuze heeft tussen een dropdown of een autocomplete input.  Anders zal bij veel gebruikers er een probleem zijn.
- [ ] moet verborgen worden indien er geen gebruikers meer zijn.

**Comment by beuntje** [comment]
bezig op branch " groepsbeheerders ", maar even aan de kant gezet wegens al te lang op aan 't bokken :-/
