### ISSUE TITLE
Notificaties op profielpagina

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#232]
Notificaties via mijn profielpagina (zie #181 en #211 )
- [x] vrijwilliger die bemiddelingsorganisatie als contact opgeeft
- [x] bij likes/bewaren op organisatie/vacature
- [x] bij aanmaken vacature

Kan bv. door in de digestentry tabel te kijken ... iedereen die daar notificaties heeft staan die bv. als flashmessage weergeven op de profielpagina (of op een andere manier)

**Comment by MKoen** [comment]
Heb wat manieren zitten zoeken om de notificaties te tonen.
Wat vind je van deze?
![notificaties](https://cloud.githubusercontent.com/assets/17765414/18950513/91302a88-8640-11e6-8a6c-5d35cf6b85ab.png)

**Comment by beuntje** [comment]
Ziet er ok uit, al zou ik het niet in het blok van de vacatures zetten. Misschien gewoon een blok erboven zonder tabblad?

**Comment by Badlapje** [comment]
en standaard toegeklapt.  Ik zou er ook ergens een aanduiding geven van het aantal notificaties, iets wat de aandacht trekt.

**Comment by MKoen** [comment]
@beuntje @Badlapje Merci, komt in orde!

**Comment by MKoen** [comment]
Is [dit](https://gfycat.com/BruisedLongInvisiblerail) dan beter? Het zit in een aparte sectie, maar de tab kan wel niet ingeklapt worden na het openen. (Ik gebruik de bestaande klassen)

**Comment by MKoen** [comment]
@Badlapje De notificaties worden nu correct uit de database gehaald en getoond. Nu ben ik bezig met de behandeling van de digests aan te passen dat ze niet verwijderd worden, maar dat de "sent" en "handled" in de database aangepast wordt. Daarnaast zal ik ook kijken voor de events toe te voegen als een gebruiker een organisatie of vacature opslaat.

**Comment by MKoen** [comment]
- Notificaties worden correct weergegeven met een knop naar de gerelateerde vacature of organisatie 
- Indien met op de knop heeft geklikt om naar die vacature of organisatie te gaan wordt de notificatie m.b.v. een boolean "Behandeld" niet meer getoond.
- DigestEntries worden niet meer verwijderd indien verzonden maar worden m.b.v. een boolean gevlagd als "Verzonden"

Nu ben ik aan het kijken om events te maken wanneer een gebruiker een vacature of organisatie heeft opgeslagen, zodat er ook eventueel een mail wordt verstuurd en een digestentry wordt aangemaakt..

**Comment by MKoen** [comment]
@beuntje @Badlapje De notificaties werken nu perfect.
[Hier een korte documentatie over hoe het systeem werkt.](https://www.dropbox.com/s/63x3wogzfc01mbw/Roeselare%20Vrijwilligt%20-%20Notificaties.md?dl=0)
Moest je nog vragen hebben, of moest er toch iets niet werken, of moest het aangepast worden, wat dan ook, laat mij iets weten. 😀 

Ik zal nu kijken voor het systeem van mails ook aan te passen zodat die ook toepasbaar zijn voor kandidaten.

**Comment by Badlapje** [comment]
joant zun

**Comment by beuntje** [comment]
#331

**Comment by beuntje** [comment]
Bij een vacature aangemaakt door een particulier (dus niet gelinkt aan een organisatie) lopen er nog dingen mis... 

(bv. bij het inschrijven op zo'n vacature:  Error: Call to a member function getAdministratorsByDigest() on null --     in src\AppBundle\Controller\UtilityController.php at line 84)

**Comment by MKoen** [comment]
@beuntje Dacht dat enkel administratoren een vacature kunnen aanmaken; het eerste wat ik donderdag ga doen is dit oplossen.
