### ISSUE TITLE
Pictogrammen bij skills/sectoren/interesses

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#238]
volgens het verzoek van Ellen

**Comment by Badlapje** [comment]
@beuntje wachten we hier op pictogrammen (van de designer)?

**Comment by beuntje** [comment]
[icoontjes.pdf](https://github.com/howest-wsde/VrijwilligersTool/files/507951/icoontjes.pdf)

**Comment by beuntje** [comment]
Icoontjes zouden vectorieel uit pdf moeten gehaald kunnen worden. Best ook vectorieel gebruiken op website dan.

**Comment by Badlapje** [comment]
? is dit zo aangeleverd?  Beetje raar formaat om afbeeldingen aan te leveren, nee?

**Comment by beuntje** [comment]
[pictos.zip](https://github.com/howest-wsde/VrijwilligersTool/files/513785/pictos.zip)

**Comment by beuntje** [comment]
#327

**Comment by beuntje** [comment]
ivm sectoren bij verenigingen, ging dit niet verwijderd worden?
