### ISSUE TITLE
Mail digest: chron job of bundle

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#239]
Grote vraag voor @beuntje stel jij die chron jobs zelf in op de server, of doen we dat bv. [via deze bundel](https://github.com/J-Mose/CommandSchedulerBundle) (op server lijkt mij simpelste)

**Comment by Badlapje** [comment]
[Zie deze commentaar](https://github.com/howest-wsde/VrijwilligersTool/issues/211#issuecomment-238525041) => kijken met chronbundle, indien het niet werkt chronjob + script ... in het kader van portability

**Comment by Badlapje** [comment]
Bundle is blijkbaar niet compatibel met elastic search bundle van FOS.  Nogo dus :(

> C:\Users\Badlapje\vagrant\homestead\RoeselareVrijwilligt\VrijwilligersTool [mailDev]> composer require jmose/command-sch
eduler-bundle
Failed loading C:\php\ext\php_xdebug-2.4.0-5.6-vc11-x86_64.dll
Using version ^1.2 for jmose/command-scheduler-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove friendsofsymfony/elastica-bundle 4.0.x-dev
    - Conclusion: don't install friendsofsymfony/elastica-bundle 4.0.x-dev
    - don't install friendsofsymfony/elastica-bundle 4.0.x-dev|install friendsofsymfony/elastica-bundle dev-master
    - Conclusion: remove ruflin/elastica 3.1.1
    - Installation request for friendsofsymfony/elastica-bundle (locked at 4.0.x-dev, required as dev-master) -> satisfi
able by friendsofsymfony/elastica-bundle[4.0.x-dev].
    - Conclusion: don't install ruflin/elastica 3.1.1
    - friendsofsymfony/elastica-bundle dev-master requires ruflin/elastica ~2.1 -> satisfiable by ruflin/elastica[2.1.0,
 2.2.0, 2.2.1, 2.3.0, 2.3.1].
    - Can only install one of: ruflin/elastica[2.1.0, 3.1.1].
    - Can only install one of: ruflin/elastica[2.2.0, 3.1.1].
    - Can only install one of: ruflin/elastica[2.2.1, 3.1.1].
    - Can only install one of: ruflin/elastica[2.3.0, 3.1.1].
    - Can only install one of: ruflin/elastica[2.3.1, 3.1.1].
    - Installation request for ruflin/elastica (locked at 3.1.1) -> satisfiable by ruflin/elastica[3.1.1].


Installation failed, reverting ./composer.json to its original content.

**Comment by Badlapje** [comment]
@beuntje heb jij die chron job(s) ingesteld op de server?  Dan kan dit gesloten worden?

**Comment by beuntje** [comment]
Welke cron moet ik instellen? Welk commando / welke timing?

**Comment by beuntje** [comment]
Ik heb voor zowel dev als www "php bin/console rv:digest 3" uitgevoerd. Is dit zoals het zou moeten?

**Comment by Badlapje** [comment]
er moet ook nog periodiciteit 2 en 4 bij (3 = wekelijks, 2= dagelijks, 4 = maandelijks).  Voor de rest zou dat moeten kloppen.

**Comment by beuntje** [comment]
ok, da's gebeurd, kan dat op een manier getest worden, want ik kreeg nog geen mails :-/

**Comment by Badlapje** [comment]
als op dev je voorkeur op "onmiddelijk" staat en je krijgt mails bij aanmaak van een gebruiker, of één van de andere zaken dan werkt het mailen.

Qua digest: je zou dat command onmiddelijk kunnen laten draaien

**Comment by beuntje** [comment]
ok, da's gebeurd, kan dat op een manier getest worden, want ik kreeg nog geen mails :-/

**Comment by beuntje** [comment]
de mail op zich is ondertussen gelukt met de volgende parameters.yml: 

    mailer_transport: sendmail
    mailer_host: /usr/bin/sendmail
    mailer_user: ~
    mailer_password: ~

**Comment by beuntje** [comment]
(laat ticket nog even open tot we zeker zijn dat cron werkt)
