### ISSUE TITLE
Logica vrijwilligers op maat

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#257]
Matching gebeurt in ES:
- [x] accessibility : afhankelijk van overeenkomst met wensen vrijwilliger een filter
- [x] longterm: afhankelijk van overeenkomst met wensen vrijwilliger een filter
- [x] verloning: afhankelijk van overeenkomst met wensen vrijwilliger een filter
- [x] sociale interactie: afhankelijk van overeenkomst met vrijwilliger een boost
- [x] overlap in skills: boost
- [x] nabijheid: sliding scale
- aantal lopende engagementen: malus gebaseerd op het aantal uur/week? => te kostelijk voor performantie
- [x] estimated work in hours: afhankelijk van wensen vrijwilliger een boost
- indien in bewaarde vrijwilligers: boost => geschrapt want momenteel bestaat er geen "bewaarde vrijwilligers" voor een organisatie
- aantal testimonials? boost met max => geschrapt want momenteel worden testimonials nog niet gelinkt aan personen
- [x] indien vrijwilliger organisatie bewaard heeft: boost met hoge waarde
- [x] indien vrijwilliger vacature bewaard heeft: boost met hoge waarde
- [x] indien vrijwilliger admin is van organisatie: kleine boost
- [x] indien vrijwilliger kandidaat is voor de vacature: kleine boost
- [x] bringing it all together in PersonController

**Comment by Badlapje** [comment]
@beuntje nog één om na te kijken

**Comment by beuntje** [comment]
indien vrijwilliger organisatie of vacature bewaard heeft: boost met hoge waarde

**Comment by Badlapje** [comment]
bonus/malus gebaseerd op aantal lopende engagementen weggelaten gezien het te kostelijk zou zijn.  [Methode om het te doen kan hier gevonden worden.](http://stackoverflow.com/questions/33316956/elastic-search-filter-by-count-of-a-nested-document)

**Comment by Badlapje** [comment]
toegevoegd aan openstaand PR #262
