### ISSUE TITLE
Recover password functionality

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#305]

**Comment by durnezj** [comment]
Hoe pak ik dit het best aan, zelf maken of gebruik maken van ingebouwde functionaliteit. Deze laatste twijfel ik of dit mogelijk is, ik vind wel hoe je een paswoord moet resetten, maar niet hoe het via email moet.

**Comment by Badlapje** [comment]
[De FOSUserBundle heeft dit ingebouwd](http://symfony.com/doc/current/bundles/FOSUserBundle/emails.html).  We gebruiken die bundle momenteel niet, maar is wslijk makkelijk om die wel te gebruiken (als ik het vlug bekijk moet onze userklasse gewoon hun userklasse extenden en presto, maar zal wslijk wel ietsje meer om het lijf hebben).  Dus als je ons user-management restyled zodat we daar gebruik van maken is dat geen probleem.

Andes zal je het idd zelf moeten implementeren (lijkt me iets moeilijker)

**Comment by durnezj** [comment]
De Person klasse wordt al een extended door OAuth, is er daar een oplossing voor? Ik dacht zelf aan PHP traits of een extra klasse om dit mogelijk te maken.

**Comment by Badlapje** [comment]
net eens gekeken, zal toch makkelijker zijn om het zelf te maken

**Comment by beuntje** [comment]
zelf maken zou redelijk eenvoudig moeten zijn: 

- extra tabel in database: passwordrecover met onderandere: person, hash, expirydate
- bij "paswoord vergeten": 
     -  check if mailaddress or telephone or username exists -> get userid & email
     -  random hash maken 
     -  hash opslaan in database + userid + expirydate (bv. 1 uur?)
     -  mail sturen naar email met link including hash
     -  op gelinkte pagina checken of gegevens kloppen
     -  nieuw paswoord laten ingeven

probleemstelling @ @Badlapje : wat bij paswoord vergeten indien geen gekend mailadres? (bv. telefoon als inlogsetting)

**Comment by Badlapje** [comment]
ik zou 5u nemen, 1u heb ik nu bij een hosting service en da's gewoon echt niet voldoende van de second er een gebruiker achter het scherm zit die niet goed weet wat hij aan het doen is (het type dat zijn passwoord verliest).

@beuntje sms-je naar de telefoon indien gsm?  En indien geen gsm mailtje naar een superadmin/beheerder die dan kan contact opnemen?

**Comment by durnezj** [comment]
Juist aan het denken, misschien moet ik deze klasse ook gebruiken voor een user die zijn paswoord niet vergeten is, maar het gewoon wil veranderen. Dit is ook basic functionaliteit denk ik.

**Comment by beuntje** [comment]
De "paswoord vergeten"-branch heb ik gemerged en de branch is gesloten. 

Alhoewel ik eerst zei dat "paswoord aanpassen" niet nodig was doordat dit bij "instellingen" kan gebeuren, kom ik op mijn woorden terug. Ik vrees dat er snel fouten gaan gebeuren als we dit daar laten staan (geen validatie op null, geen dubbele invoer, ... ). 

Dus: goed idee: graag ook een "paswoord aanpassen" voorzien :-D

**Comment by durnezj** [comment]
Dit werkt volledig, mag deze gesloten worden dan?
