### ISSUE TITLE
Vertaling niet-email

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#306]
alle kernwoorden die @beuntje  erin gezet heeft maar niet in de engelse tegenhanger staan.

**Comment by beuntje** [comment]
Ik heb op de release-tool een scriptje gezet: http://release.roeselarevrijwilligt.be/comparetranslations.php?f=dev ... met deze kun je makkelijker vergelijken

**Comment by deblaererobin** [comment]
ik vind nergens het wachtwoord terug voor in te loggen

**Comment by beuntje** [comment]
http://wiki.wsde.be/Release.roeselarevrijwilligt.be

**Comment by beuntje** [comment]
hmm, ik zie dat jullie nog niet in de wiki zitten... ik voeg jullie straks toe

**Comment by deblaererobin** [comment]
geen probleem ;)

**Comment by deblaererobin** [comment]
dus ik moet nog een engelse vertaling doen en de omzetting van de mails?

**Comment by beuntje** [comment]
Het vertalen van de mails is eigenlijk ticket #244 ... dit ticket hier gaat idd over de engelse vertallingen. Kies maar: of je doet beide tickets, of je verandert je assignee-status in beide tickets.

**Comment by deblaererobin** [comment]
zal dan best de beide doen met dat ik toch bezig ben

**Comment by deblaererobin** [comment]
done!
