### ISSUE TITLE
Testimonials inwerken in het systeem

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#307]
- [x] dashboard vrijwilliger
- [x] dashboard organisatie

**Comment by MKoen** [comment]
Ben druk bezig met te kijken hoe ik het het best kan implementeren. Heb bij de entiteit *Testimonial* een boolean "receiverIsVacancy" toegevoegd zodat het gemakkelijk is om te zien of *receiver_id* een vrijwilliger of een vacature is. Ben nu ook aan het kijken om de twig pagina's toe te voegen samen met de form en de controller. 
@Badlapje waar zou jij het liefst de knopjes zien voor de vrijwilligers en voor de vacatures om een getuigschrift te versturen naar elkaar?

**Comment by beuntje** [comment]
Ik denk dat het beter is in plaats van receiverID te werken met een receiverPerson en receiverVacancy. Deze kan je dan in doctrine en de entity rechtstreeks koppelen aan het juiste entity.  Een van de twee velden moet dan ingevuld zijn, de andere 0 / null.

**Comment by MKoen** [comment]
@beuntje Inderdaad beter, merci!

**Comment by MKoen** [comment]
@beuntje De basisfunctionaliteiten van de getuigschriften zijn af.
Als vrijwilliger van een vacature kan je een getuigschrift maken en als administrator van een organisatie kan je een getuigschrift sturen over een vacature naar een vrijwilliger van die vacature sturen.

Als vrijwilliger krijg je een notificatie en een mail als je een getuigschrift ontvangen hebt en kan hij deze zien op zijn profiel pagina.

Als een organisatie een getuigschrift heeft ontvangt dan krijgen alle administratoren een notificatie met een link naar de vacature. Daar staan er 2 tabs: Getuigschriften en Getuigschriften in behandeling. Deze die goedgekeurd zijn staan in de 1e tab en kan iedereen zien. Deze die nog niet goedgekeurd zijn staan in de 2e tab en kunnen enkel administrators van toepassing zien. Zij kunnen dan het getuigschrift goedkeuren of verwijderen. Indien goedgekeurd wordt deze zichtbaar voor iedereen.
