### ISSUE TITLE
Map preview bij edit profiel (instellingen)

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#308]
moet nog gemaakt worden, enkel divke zit er al in

**Comment by durnezj** [comment]
https://github.com/howest-wsde/VrijwilligersTool/pull/315

**Comment by beuntje** [comment]
![screen](https://cloud.githubusercontent.com/assets/3738113/19551988/32f0a938-96ae-11e6-9d1b-0dc72d3f9bc7.png)

ter info over de huidige versie op branch "dev": ik kreeg deze zonet lokaal bij het klikken op "instellingen". Mijn profiel heeft nog geen gekende adresgegevens.

**Comment by durnezj** [comment]
Oeps, ik zie dit maar laat, dit was iets dat ik overzien had. Normaal komt dit in de console, maar ik heb het ter debugging even in een alert gezet. Normaal is dit ondertussen al gefixed.

**Comment by beuntje** [comment]
#337
