### ISSUE TITLE
Zoekpagina 

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#312]
- [x] zoekblok naar boven (zie wireframes)
- [ ] zoeken op personen beperken tot enkel naamveld

**Comment by beuntje** [comment]
#321

**Comment by deblaererobin** [comment]
wat is juist de bedoeling van deze issue?

**Comment by beuntje** [comment]
probleem was dat elastic search ingesteld stonnd dat bij het zoeken naar personen, ook gerelateerde personen (bv. via vacature) ook teruggegeven werden. Op 't eerste zicht is dit niet meer het geval. Ik zal deze dus sluiten.

**Comment by beuntje** [comment]
Correctie: als je zoekt op bv. "roeselare" krijg je alle personen die in Roeselare wonen. Dit is niet de bedoeling. Elastic search mag enkel naam indexeren
