### ISSUE TITLE
weergave bugs in Safari

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#316]
probleem met flex?  Zie hieronder
![safaribug 1](https://cloud.githubusercontent.com/assets/4058016/19148339/8598da40-8bbc-11e6-9c19-327c20ff5f5c.png)
![safaribug 2](https://cloud.githubusercontent.com/assets/4058016/19148342/8b06ba10-8bbc-11e6-81c3-ce9a11a7b345.png)
![safaribug 3](https://cloud.githubusercontent.com/assets/4058016/19148343/8b1b0628-8bbc-11e6-8fc1-43004c020d64.png)

**Comment by MKoen** [comment]
@Badlapje Heb dit net getest met Safari op een Macbook Air en site werd perfect weergegeven. Op welke versie van Safari is die screenshot genomen?
