### ISSUE TITLE
kaartje op homepage

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#330]
Er zou bovenaan op de homepage een kaartje moeten komen met bullets van waar verenigingen en/of vactures te vinden zijn.

**Comment by beuntje** [comment]
@durnezj , ben jij hiermee bezig? Wanneer denk je dit te hebben?

**Comment by durnezj** [comment]
@beuntje Ik zal er vandaag beginnen aan werken.

**Comment by beuntje** [comment]
#344
