### ISSUE TITLE
Google maps issue

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#342]
Er is nog een probleem met de google-api-JS (TypeError: a is undefined) bij het laden van js/livemap.js. Als er andere scripts geladen worden na de livemap gaan deze niet uitgevoerd worden! 

edit: probleem gekregen op /vrijwilliger_worden

**Comment by beuntje** [comment]
Mogelijke piste is dat dit enkel voorkomt als er geen map bestaat: bv /vrijwilliger_worden als er al ingelogd is. Wordt er in livemap.js gecontroleerd of er effectief een map bestaat?

**Comment by durnezj** [comment]
@beuntje Dit was inderdaad het geval, ik heb een check toegevoegd die kijkt of een kaartje aanwezig is op de site en indien nodig dan de functies inlaadt. da052faf07bdc9aa6fe7e41a75ada416f773da6d

**Comment by durnezj** [comment]
@beuntje deze bug is opgelost in de dev, mag deze dan gesloten worden?
