### ISSUE TITLE
testing op live (vraag van kurt): kleine UX probleempjes

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#349]
- [x] Vrijwilliger worden: buttons bij "voordelen voor de vrijwilliger": naast elkaar zetten
- [x] Ook als er geen bewaarde vacatures zijn staat er een titel "bewaarde vacatures" op de "word vrijwilliger"-pagina
- [x] Op de profielpagina staat "bewaarde vacatures" in een 2e tab, "bewaarde organisaties" staat op de 3e tab. Beide op 2e plaats zetten
- [x] In de mail "nieuwe kandidaat" staat de url naar de vereniging relatief, ipv absoluut (ook andere mails checken)
- [x] Click op tabblad van formulier: scrollen naar juiste positie
- [x] bij aanmaak van een vereniging wordt er gevraagd om sectoren aan te vinken, maar er zijn geen sectoren meer => sectoren vervangen door interesses/vaardigheden 
- [x] bij alle accordeons is enkel de link zelf met een handje als je erboven zweeft ipv. de volledige "button".  Daarnaast is er ook nergens een aanduiding dat dit om accordeons gaat (een pijltje naar beneden aan de rechterkant bv. zou dat oplossen).
- [x] Net opgemerkt dat in het overzicht van bewaarde vacatures (dashboard) er niets veranderd als je een vacature "ontwaard" of een andere bewaard, tenzij je reload.  Dit zou via jquery eenvoudig kunnen rechtgezet worden.
- mijn testvereniging FB Meetjesland (werd verwijderd) heeft op live geen openstaande/afgesloten/onafgewerkte vacatures maar:
   - [x]  2 onbeantwoorde kandidaten (zonder link waar ik op kan klikken
   - [x] 3 tabs zonder iets in, wat knap verwarrend is
- bij de zoekpagina: 
   - [x] moet filter op sector weg
   - [x] zie ik bij de filters telkens het engelse woord in het klein staan onder de filters (interesses => categories, sector => sectors, ...)?
   - [x] de twee text inputs bij de filters zou ik een klein beetje padding geven langs de linkerkant, nu staat die 0 zo dicht op de rand geplakt.
- [x] recenten en bewaarde zoekopdrachten gaan nog niet op de live => beter om die tekst voorlopig weg te laten bij de zoekblokken
- [x] vzw voc opstap heeft 4 openstaande vacatures volgens, maar er worden er maar 3 getoond op de verenigingspagina?
- [x] mailadres en telefoon bij verenigingen zijn niet aanklikbaar? (geen mailto en tel)
- bij vrijwilliger vinden 
   - [x] kan ik de 2 verenigingen die gedelete zijn selecteren als vereniging waarvoor ik een vacature wil aanmaken.
   - [x] is niet de volledige tile van de vereniging aanklikbaar
   - [x] is de titel van de vereniging een link naar die vereniging, wat in die context raar is misschien => uit te testen!
- bij aanmaak van een nieuwe vacature
   - [x] sector staat nog tussen interesses, dat zou niet meer moeten 
   - [x] zijn verwijderde verenigingen zichtbaar 
   - [x] zijn de tekstvakken bij beknopte omschrijving en jobinhoud wel bijzonder klein
   - [x] krijg ik een notificatie indien bij bewaar en publiceer later, ook al heb ik de vacature zelf aangemaakt
   - [x] staat er bij een onafgewerkte vacature nergens een aanduiding dat die onafgewerkt is (icoontje of zoiets)
   - [x] staat er bij mijn profiel, blok onafgewerkte vacatures, een knop "lees meer" ipv. een knop "publiceer" & een knop "bewerk vacature"
   - [x] staat de knop "plaats vacature" en "bewaar vacature" verborgen.
   - [x] heeft de knop annuleren geen opmaak als knop, en is die veel breder dan alle andere knoppen => inconsistent en verwarrend voor de gebruiker
   - [x] staat het euro-teken in het midden van de input (ipv. mooi op dezelfde lijn als de tekst) en volledig tegen die input aan geplakt
- [x] Een vacature die je eerst bewaarde en erna probeert te plaatsen geeft wel een succesboodschap, maar blijft in je "onafgewerkte vacatures"-tab komen op je profielpagina.  Ze komt ook niet in recente vacatures in de footer.
- [x] ik kan nergens aan de verwijderde vacatures, tenzij ik de rechtstreekse link ken.  
- [x] ik kan een vacature niet "afsluiten", enkel verwijderen (afgesloten vacatures die komen wel in een tab waar ik er aan kan).
- [x] ik kan afgesloten vacatures niet dupliceren, er komt ipv. een "lees meer knop"
- [x] bij partners is enkel het logo aanklikbaar, niet het volledige kaartje
- [x] idem bij vacatures
- [x] bij "hoe werkt het" en "verhalen" is er geen terug knop, en ook geen knop om door te schakelen naar 1 van de vier andere blokken.  Mensen die de back button niet kennen (zijn er nog veel) lopen hier wat verloren.  Idem bij de uitgebreide info voor vrijwilligers/organisaties.
- [x] bij vrijwilligersinfo springen de "lees meer in ... " er niet uit als buttons om op door te klikken.  Beter om hier consistent te blijven met de rest van de site waar buttons een duidelijke layout hebben.
- [x] bij verhalen en de uitgebreide info voor vrijwilligers / organisaties zijn er geen pijltjes / blok om terug naar boven te springen.
- [x] broodkruimels ontbreken op alle pagina's
- [x] aan het einde van de test ontbreken nog buttons om door te klikken + eventueel al vacatures op maat.
- [x] interesses worden niet aangepast op basis van de test.
- [x] bij interesses en voorkeuren staat alles wat dicht op elkaar
- [x] tekstvak bij "contacteer ons" is behoorlijk klein
- bij de carrousel op de homepagina 
   - [x] is het niet onmiddelijk duidelijk dat het over verschillende zaken gaat aangezien de achtergrondafbeelding en layout (titel, tekstvlak) altijd hetzelfde blijven. 
   - [x] bij de kaart is het niet duidelijk dat dit om een overzicht van de verenigingen gaat... hier mankeert een titel.  De zoom misschien ook aanpassen?
- bij vrijwilliger aanmaken
   - [x]  is de knop zoeken bij "zoek naar vacatures" niet zoals andere knoppen op de site, maar precies een tweede zoekveld.  Bijzonder verwarrend.
   - [x] staat bij "maak een profiel aan" geen knop naar de volgende stap, enkel een knop "maak account", als je die indrukt verlies je gelijk de mogelijkheid om bijkomende informatie in te vullen ... wat absoluut NIET goed is.
   - [x] bij de mail die je krijgt na aanmaken van account staat alles vanaf "met vriendelijke groeten" op dezelfde lijn.
   - [x] bij "contactgegevens" staan de knoppen "volgende" en "terug naar registratie" op een verschillende lijn ipv. naast elkaar.
   - [x] de knop "terug naar registratie" bij "contactgegevens" zou beter "terug naar profiel aanmaken" heten (of je moet "profiel aanmaken" veranderen naar "registreren")
   - [x] bij "interesses en voorkeuren" staat alles heel dicht bij elkaar.  Daarnaast zijn de interesses / capaciteiten niet evenveel ingesprongen als alle andere items, wat er raar uitziet.
   - [x] bij "kijk welke vacatures interessant zijn 
   - [x] er staat nog steeds een verloren knop "indienen" onder de accordeon "interesses en voorkeuren"
   - [x] bij "kijk welke vacatures interessant zijn" verwachten mensen een blok "vacatures op maat, "recente vacatures" & de mogelijkheid om te zoeken naar vacatures.  => de accordeon "bekijk de spelregels" kan dan ook beter boven deze accordeon geplaatst worden.
   - [x] bij "kijk welke vacatures interessant zijn" is de link naar de test geen button, wat er raar uit ziet (die zou mooi gecentreerd kunnen worden met twee lijnen (zoals in de wireframe).
   - [x] stel je kandidaat mocht weg als ik mij niet vergis, mensen vinden die extra info niet nuttig / nodig
- [x] bij inloggen kan "nog geen login" en "maak een account" gecombineerd worden in 1 button (die dan ook enkel de lengte heeft van die button en gecentreerd staat)
- [x] bij alle verenigingen staan ook verwijderde verenigingen

**Comment by Badlapje** [comment]
op vraag van Kurt dit weekend de site getest op usability.  Dit kwam er uit.  Merendeel zijn kleinere zaken qua opmaak die op 1 dag kunnen rechtgezet worden.  Hier en daar wat grotere dingen die wslijk nog altijd simpel recht te zetten zijn.

**Comment by beuntje** [comment]
@ iedereen : Graag vóór het aanpakken van issues eerst de checkbox aanvinken.

**Comment by MKoen** [comment]
Ben ervoor aan het zorgen dat een deel van de pagina gerefreshed wordt bij het liken of unliken van vacatures/verenigingen.

**Comment by MKoen** [comment]
@Badlapje 
> bij aanmaak van een vereniging wordt er gevraagd om sectoren aan te vinken, maar er zijn geen sectoren meer => sectoren vervangen door interesses/vaardigheden

@deblaererobin en ik zaten te denken of het anders niet gemakkelijker zou zijn om gewoon op de pagina van een vereniging alle distinct _skills_ automatisch te tonen die aanwezig zijn op hun vacatures. Dit zorgt ervoor dat die altijd juist zijn en zo kunnen administratoren ook geen _skills_ toevoegen die niet gebruikt worden.

PS: Indien je toch liever hebt dat een administrator toch dat zelf kan toevoegen bij het maken of aan te passen van een organisatie, gaan we het zo wel doen :-)

**Comment by MKoen** [comment]
@Badlapje

> Vrijwilliger worden: buttons bij "voordelen voor de vrijwilliger": naast elkaar zetten

Bedoel je hiermee niet "Vrijwilliger vinden"?

**Comment by SnelleJelle** [comment]
geen broodkruimels maar ik ga de issue wel sluiten
