### ISSUE TITLE
verkeerd e-mailadres geeft foutmelding

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#381]
koen:cornelis@vanonderen.be geeft fout : [2016-11-17 12:27:17] request.CRITICAL: Uncaught PHP Exception Swift_RfcComplianceException: "Address in mailbox given [koen:cornelis@vanonderen.be] does not comply with RFC 2822, 3.6.2." at /home/admin/web/roeselarevrijwilligt.be/symfony/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php line 347 {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [koen:cornelis@vanonderen.be] does not comply with RFC 2822, 3.6.2. at /home/admin/web/roeselarevrijwilligt.be/symfony/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:347)"} []

**Comment by MKoen** [comment]
@beuntje Zit dat e-mail adres misschien verkeerd in de database? Want normaal kan je toch geen account/vereniging aanmaken of aanpassen met en verkeerd e-mail adres?
![image](https://cloud.githubusercontent.com/assets/17765414/21393434/b0ebab5a-c794-11e6-9c29-80370c3513de.png)
