### ISSUE TITLE
foutmelding gebruikersnaam: geen spaties

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#382]
onduidelijke foutmelding als er een gebruikersnaam met spatie ingevuld wordt

**Comment by MKoen** [comment]
@beuntje Mag de melding die getoond wordt bij invalid input mbv js aangepast worden?

**Comment by MKoen** [comment]
@beuntje Nu worden er custom validity messages getoond aan de gebruiker wanneer hun voor- en achternaam niet enkel letters, cijfers, spaties of koppeltekens bevatten en als hun username niet enkels letters en cijfers bevatten. Deze worden nu ook volledig vertaald. Je info attributes heb ik ook vertaald gemaakt. (Samen met een kleine GUI fix, want de infopop van de wachtzin kwam onder de textbox te staan.

Ik heb ook dev2 gemerged met dev-usernameFix

Ik ga nu anders kijken om de tabs waarin er een validity message komt automatisch actief te maken, zodat de gebruiker gemakkelijker kan zien wat er fout is ingegeven.
