### ISSUE TITLE
nieuwe gebruiker: 2e tabblad

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#386]
als adres blanco is, toon ook 2e tabblad op "word vrijwilliger"

**Comment by MKoen** [comment]
@beuntje Wat bedoel je hiermee? Welke tablad moet er getoond worden bij word vrijwilliger als er geen adres is ingegeven?

**Comment by MKoen** [comment]
@beuntje ok, ik zal daar voor kijken
