### ISSUE TITLE
vacature als persoon zonder vereniging

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#387]
beheersmogelijkheid?

**Comment by MKoen** [comment]
Ik zal kijken om dat op te lossen.

**Comment by beuntje** [comment]
hmm, ondertussen had ik dit al aangepakt...

**Comment by beuntje** [comment]
op de hoofdpagina van een gebruiker kan hij/zij nu ook een overzicht van eigen vacatures zien, en op de vacature zelf staat ook een aanpasknop

**Comment by beuntje** [comment]
ik weet niet meer zeker of ze ook kandidaten kunnen bevestigen / afwijzen, maar ik denk het wel. Dit best eens nakijken

**Comment by MKoen** [comment]
@beuntje Oke, zal het eens testen. Als het werkt dan doe ik mijn branch weg en werk ik op een andere issue :)

**Comment by MKoen** [comment]
@beuntje als ik een kandidaat wil accepteren krijg ik een error van de notificaties (getAdministratorsByDigest() ), ik zal kijken om dat op te lossen

**Comment by MKoen** [comment]
Notificaties en mails voor particuliere vacatures werken nu ook. Zal er pull request maken.
