### ISSUE TITLE
Fatal doctrine error when populating Elastica Index

### ISSUE THREAD

**Issue by deblaererobin** [howest-wsde/VrijwilligersTool#40]
- php bin/console fos:elastica:populate throws error
     - PHP Fatal error:  Call to a member function getRepository() on null
     - VrijwilligersTool/vendor/friendsofsymfony/elastica-bundle/Doctrine/ORM/Provider.php

     -  [Symfony\Component\Debug\Exception\FatalErrorException]   
         Error: Call to a member function getRepository() on null

**Comment by SnelleJelle** [comment]
stackoverflow: [http://stackoverflow.com/questions/36623920/fatal-doctrine-error-when-populating-elastica-index](http://stackoverflow.com/questions/36623920/fatal-doctrine-error-when-populating-elastica-index)

**Comment by SnelleJelle** [comment]
@deblaererobin  @durnezj  is dit al opgelost?

**Comment by deblaererobin** [comment]
Het werkt nu weer perfect bij thibault,

**Comment by durnezj** [comment]
Sindsdien een fresh install gedaan van alles en het werkt terug.

**Comment by SnelleJelle** [comment]
SUPER!, mag de issue gesloten worden?

**Comment by durnezj** [comment]
jazeker:-)
