### ISSUE TITLE
!! important !! Foutje in "instellingen"-pagina. 

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#404]
In de live-database zitten een 10-tal gebruikers van bv. Koen. Hij heeft echter max. 2 accounts aangemaakt, maar wel verschillende keren profiel aangepast.  

- [x] Nakijken of er niet gewoon een nieuwe gebruiker aangemaakt wordt bij save instellingen-page. 
- [ ] Uitzoeken wat de reden dan wel is

**Comment by beuntje** [comment]
[ ] Nakijken of er niet gewoon een nieuwe gebruiker aangemaakt wordt bij save instellingen-page.
> is niet het geval !!

**Comment by MKoen** [comment]
Op mijn lokale database heb ik als een duplicaat gekregen door de instellingen aan te passen, maar ik heb nu net meermaals al mijn gegevens aangepast en het account wordt niet gedupliceerd. Dusja, was het een one-time glitch? Want ik kan het niet direct herhalen. (Oftewel manier nog niet gevonden van bug)

**Comment by beuntje** [comment]
Ik snap de zin "Op mijn lokale database heb ik als een duplicaat gekregen door de instellingen aan te passen" niet... Heb je het opnieuw voorgehad of niet? 

Ik heb me ook nog bedacht dat je misschien op de live-omgeving accounts aangemaakt hebt in de veronderstelling dat je op dev bezig was, maar dev.roeselarevrijwilligt.be linkt al een tijdje door naar de live omgeving. Misschien was dit het probleem?

**Comment by MKoen** [comment]
@beuntje Ik betwijfel of het door de instellingen kwam, ik heb waarschijnlijk dan wel ooit eens 2 accounts op lokale databank gemaakt.

En zou misschien wel mogelijk zijn, sorry daarvoor.

Maar I guess dat het probleem nu opgelost is? :)
