### ISSUE TITLE
foutmelding geven bij te grote logo's

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#414]
Bij te grote bestanden voor logo vereniging wordt een fout gegeven en ziet de gebruikers niets meer. Dit moet een melding worden dat het bestand te groot is. 

[2016-12-19 11:03:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpFoundation\File\Exception\FileException: "The file "SI_logo_DD_cmyk.jpg" exceeds your upload_max_filesize

**Comment by MKoen** [comment]
@beuntje zal kijken om dat op te lossen

**Comment by durnezj** [comment]
Net eens geprobeerd en het is zelfs mogelijk om niet-afbeeldingen zoals javascript files en .exe bestanden up te loaden, dus is er ook geen check op MIME-types?

**Comment by MKoen** [comment]
@durnezj ik ben daaraan bezig. Enkel .png en .jp(e)g bestanden accepteren samen met een file size limit.

**Comment by beuntje** [comment]
best ook oplossen dus :-)
in plaats van (enkel) op mime-type misschien ook onderstaande gebruiken om zeker te zijn dat het een image is. 
`if(getimagesize($filepath) !== false) { // is image: ok`

**Comment by MKoen** [comment]
@beuntje Wat is de default upload path van zo'n bestanden? Via ````$organisation->getLogoName()```` kom in aan de naam met de extentie, maar weet ik de locatie niet. En met ````$organisation->getLogoFile()```` kom ik wel aan de file zelf, maar ````getimagesize```` vraagt het pad.

**Comment by beuntje** [comment]
(web)/images/organisations/

**Comment by MKoen** [comment]
@beuntje Sorry voor de regen van vragen hoor, maar ik heb even een opklaring nodig. Als ik een te groot bestand upload zie ik ````Warning: POST Content-Length of 5516213 bytes exceeds the limit of 3145728 bytes in Unknown on line 0```` boven de pagina. Maar blijf ik de site zelf wel zien. Boven het formulier zie ik  zelfs al een melding dat het geüploade bestand te groot is (wel nog niet dat het geen image is). 

Hier een paar screenshots:
![Bovenkant formulier](https://cloud.githubusercontent.com/assets/17765414/21353643/4175b554-c6c7-11e6-8319-ebee7212b0f1.png)

![Bovenkant site](https://cloud.githubusercontent.com/assets/17765414/21353663/53301b9a-c6c7-11e6-8b38-5342c434e160.png)


Toont de server bij jou misschien enkel maar die warning en niets anders?

**Comment by beuntje** [comment]
Het is op de live omgeving - bij een gebruiker - dat de fout gebeurd is. Ik veronderstel dat warnings daar ook een 500-error geven en dus de standaard fout-pagina geven. (zonder specifieke melding). De foutmelding die ik in de issue plaatste komt uit de serverlogs

**Comment by MKoen** [comment]
@beuntje Na de ````post_max_size```` te vergroten in `````php.ini```` zodat de file kleiner is dan die limit krijg ik inderdaad een volledige 500 error. Ik zal kijken om dat op te vangen. (Maar er blijft toch wel altijd een limit voor post requests, dus je zal toch altijd een file kunnen uploaden die groter is dan die limit, dus opnieuw die error krijgen?)

**Comment by beuntje** [comment]
filesize kan client-side gevalideerd worden met javascript. 
http://stackoverflow.com/questions/3717793/javascript-file-upload-size-validation

**Comment by MKoen** [comment]
@beuntje Ik was aan het twijfelen om het inderdaad met javascript te doen. Maar is dat dan niet erg als er mensen zijn die geen javascript hebben? (voor zover er zo'n mensen bestaan)

**Comment by beuntje** [comment]
ik denk dat dit publiek zich beperkt tot heel paranoïde mensen + mensen met visuele beperking die screenreader of brailleregel gebruiken... In beide gevallen is het uploaden van images in hun geval ook onwaarschijnlijk, en indien ze het toch doen krijgen ze dan maar de error-500-pagina

**Comment by MKoen** [comment]
@beuntje Goed punt 😄 Ik zal toch kijken om op te vangen als het geen afbeelding is, want dat is toch niet zo onbelangrijk.

**Comment by MKoen** [comment]
@beuntje Sorry voor mijn wall of questions vandaag. Na vanmiddag veelal uit te zoeken hoe ik dit probleem kan oplossen server-side, is het misschien inderdaad het best om dat via javascript te doen.

Het eerste dat ik morgen zal doen is kijken om dit client-sided te laten controleren en een gepaste message te tonen. En als de user handmatig geen javascript draait, of die zelf aanpast, moet het maar een 500 response krijgen

**Comment by MKoen** [comment]
@beuntje Voila, als de gebruiker javascript heeft en er niets aan veranderd heeft, krijgt het een alertje als de afbeelding geen echte afbeelding is of als het groter is dan 2MB. Voor de zekerheid wordt er niet gecontroleerd door naar de extensie te kijken, maar door naar de file signatures te kijken. :-)
