### ISSUE TITLE
Implement Account Kit

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#45]
https://developers.facebook.com/blog/post/2016/04/12/grow-your-app-with-account-kit/

allows for logging in with only a phone number

**Comment by durnezj** [comment]
Ben begonnen met research hoe het werkt en we het kunnen implementeren.

**Comment by durnezj** [comment]
Ik vind nergens een versie voor PHP, enkel een implementatie voor node.js.

**Comment by Badlapje** [comment]
@durnezj Account Kit werkt langs de client-side, en stuurt dan zaken door naar de server.  De implementatie voor node.js is niet meer dan een voorbeeld om duidelijk te maken wat er moet gebeuren.  Kan je dus perfect ook in php doen, je zal alleen niet kunnen copy/pasten ;-)

Of zoals zij het zeggen:

> You may choose to use any technology (such as PHP or Python) to implement your server. The Node.js implementation below is a suggested example.

**Comment by Badlapje** [comment]
Thibault man, in het 2e jaar moet je google kunnen gebruiken, 30 seconden opzoekwerk: https://github.com/elaniin/AccountKit-Web-PHP

**Comment by durnezj** [comment]
Ik krijg telkens volgende error als ik het lokaal wil testen. Heb al het domain enzo aangepast maar de error blijft zich voordoen.

Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

**Comment by MKoen** [comment]
@durnezj localhost staat niet in de app domain field van onze facebook app, maar localhost is ook niet toegestaan om daarin te staan. Daarom lukt dat niet om dat lokaal te testen

**Comment by durnezj** [comment]
Ik heb dit al geprobeerd en werkt ook niet, zelfs al geprobeerd aliassen in de hosts file te steken maar tevergeefs.

**Comment by durnezj** [comment]
Is er een oplossing hiervoor, zoals op de dev.roeselarevrijwilligt.be kunnen testen of kan ik het eerst proberen maken op een eigen server?

**Comment by MKoen** [comment]
@durneztj Toen ik eraan werkte heb ik mijn eigen server hierboor gebruikt. Die is wel gratis, en komt van Byethost. Maar doet wat het moet. Je kan dan ook eventueel een nieuwe facebook app maken dat je een andere app id en secret hebt, maar je kan ook gewoon een testversie aanmaken van onze bestaande fb app. Ik voeg je anders toe als beheerder, dan heb je er toegang voor

**Comment by SnelleJelle** [comment]
Het probleem lijkt al opgelost te zijn! super!
Indien je zo'n dingen ook op een _subdomain_ kan testen kan je een _subdomain_ name aanvragen voor je eigen computer via services zoals http://www.noip.com/

**Comment by durnezj** [comment]
@Badlapje Ik heb nu alles va

**Comment by durnezj** [comment]
@SnelleJelle Dit is de error die ik bedoelde.
http://imgur.com/bsNgnXV

**Comment by SnelleJelle** [comment]
@durnezj  kan je je code op een branch zetten zodat ik het geheel kan bekijken?

**Comment by durnezj** [comment]
Ik heb het nog niet geintegreerd in het symfony project, maar het is letterlijk de code van op die andere git. 
http://pastebin.com/5dWaga4Z/?e=1

Hier vindt je de code die nu op die site werkt, ik herschrijf en integreer het dan in het project als deze fout er uit is.

**Comment by SnelleJelle** [comment]
@durnezj Ik krijg geen sms, noch een e-mail van facebook.
wel zie ik in de console.log staan: `inited`.

**Comment by SnelleJelle** [comment]
@durnezj moeten die nummers en e-mailadressen gekend zijn bij facebook om de account kit te kunnen gebruiken?

**Comment by durnezj** [comment]
dat is vreemd, de gegevens die ik submit zijn ook niet gekend en werken wel, ik zal eens de Facebook app settings aanpassen.

**Comment by Badlapje** [comment]
ik kijk morgen es, zat in Ierland voorbije dagen.

**Comment by SnelleJelle** [comment]
@Badlapje

**Comment by durnezj** [comment]
Update: ik heb response op de issue gekregen met een fix die zou moeten werken. Ik implementeer deze na mijn examens :-)
