### ISSUE TITLE
Dummy test data aanmaken

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#55]
what she said

**Comment by Badlapje** [comment]
@durnezj @deblaererobin 
Hebben jullie hier al naar kunnen kijken?

**Comment by durnezj** [comment]
Ja, ik denk dat Robin hier nu me bezig is.

**Comment by durnezj** [comment]
@SnelleJelle ik ben dummy data aan het maken, maar wat betekent de kolom parent_id in de tabel skill?

**Comment by beuntje** [comment]
Waarschijnlijk is het de bedoeling dat skill een hiërarchische structuur is: 
1. architectuur (parent 0)
2. informatica (parent 0)
    3. webtechnologie (parent 2)
           5. php (parent 3)
           6. html (parent 3)
    4. hardware (parent 2)

**Comment by SnelleJelle** [comment]
@durnezj Inderdaad wat @beuntje zei. Een Skill heeft een naam en valt onder een andere Skill(categorie/parent). De hoogste parent in de hiërarchie heeft als _parent_id waarde null_

**Comment by SnelleJelle** [comment]
@durnezj kleine wijziging in de database:
Een bus wordt een string die een alphanumerieke waarde kan bevatten. bus komt voor in organisation & person.

**Comment by Badlapje** [comment]
ziet er goed uit :-)
