### ISSUE TITLE
Facebook sharing button not working/showing anymore

### ISSUE THREAD

**Issue by durnezj** [howest-wsde/VrijwilligersTool#57]
The implemented and working facebook sharing button does not work anymore, when it did before.
Maybe some script changes like the facebook login caused it to not show up anymore.

**Comment by durnezj** [comment]
This bug only seems to occur on my firefox, its is working on chrome/chromium and everything else.
So the bug is on my side.

**Comment by SnelleJelle** [comment]
Ondertussen al gevonden waarom het niet werkte?

**Comment by durnezj** [comment]
jup, het lag stomweg aan mijn adblocker op firefox die facebook blokeerde.

**Comment by Badlapje** [comment]
dus dit mag afgesloten worden?
