### ISSUE TITLE
Creating installation guide vm's

### ISSUE THREAD

**Issue by deblaererobin** [howest-wsde/VrijwilligersTool#76]
Ben bezig in python, aan het zoeken om een lijstje te krijgen met alle woorden die jelle tussen <> gezet heeft samen te krijgen en waar die precies staan.
Misschien heeft iemand een best practise om dit te doen? 
Ik had al gedacht om gewoon iedere lijn te overlopen? daarna te controleren welk woord er in staat en daarna vragen om een mogelijkheid te kiezen?

**Comment by SnelleJelle** [comment]
Je zal sowiese elke regel moeten overlopen. Elk van de regels die <IETS> bevat is een regel met een parameter die opgevuld moet worden. Op dat moment moet er aan de user gevraagd worden om een waarde in te geven of een waarde te kiezen(op basis van suggestie). Die waarde die de user dan ingeeft komt te staan op de plaats van <IETS>.

**Comment by Badlapje** [comment]
je kan perfect het woord <IETS> vervangen door bv. <<Geef een wachtzin in voor de administrator account | /validatie regex/>> om het makkelijker te maken => op die manier kan je via split zowel de vraag voor de gebruiker als de validatie krijgen en wordt het script zeer dynamisch (dan maakt het niet meer uit of er extra parameters gevraagd gaan worden of niet).

**Comment by deblaererobin** [comment]
http://pastebin.com/4RxbXa6m 
ik zit vast om het opvangen van een soort van verkeerde input om die dan opnieuw terug te vragen.
dit gebeurt op lijn 25 en 26.

**Comment by SnelleJelle** [comment]
@deblaererobin 
kijk eens naar deze sample code: [http://pastebin.com/EkhzSCDj](http://pastebin.com/EkhzSCDj).
Je kan dit makkelijk omvormen naar een fuctie die je dan oproept met parameters

**Comment by SnelleJelle** [comment]
@deblaererobin 
deze sample code is leuk om te vinden waar de **<TAGS>** zitten: [http://pastebin.com/RzgLqK2x](http://pastebin.com/RzgLqK2x)

**Comment by SnelleJelle** [comment]
@deblaererobin hoever staat de voortgang? Heb je hulp nodig?

**Comment by deblaererobin** [comment]
die user input validation code werkt gelijk niet dus, met die andere code zal ik ook wel iets kunnen doen denkik, heb ook al zitten zoeken naar een best practise of voorbeeldcode

**Comment by SnelleJelle** [comment]
@deblaererobin kom anders eens langs in b211?

**Comment by deblaererobin** [comment]
omw

**Comment by deblaererobin** [comment]
http://pastebin.com/Wuc4hGAF

hier mee ben ik nu bezig, nu is het nog wat omslachtig, mss zou het beter zijn om dan een gewone functie stelvraag(bits)
die dan automatisch de ingevulde waarde dan in de array stopt

**Comment by SnelleJelle** [comment]
@deblaererobin Ziet er nog heel ruw uit maar mijn snippets zien er in het begin ook heel ruw uit. Als je ergens te lang bij vastzit of ergens niet zeker van bent, aarzel dan niet om het te vragen.
gl!

**Comment by Badlapje** [comment]
@deblaererobin waarom werk je daar met while lussen die als conditie altijd true zijn?  Die kan je toch gewoon weglaten?

**Comment by deblaererobin** [comment]
zonder gaat het ook danku @Badlapje

**Comment by deblaererobin** [comment]
Ma

**Comment by SnelleJelle** [comment]
@deblaererobin al voortgang gemaakt? post eens wat je hebt?

**Comment by deblaererobin** [comment]
@SnelleJelle 
heb zitten uitzoeken hoe je bij foute input dat kunt opvangen en zorgen dat er een juiste waarde wordt ingegeven
http://pastebin.com/FzeBHg38

**Comment by SnelleJelle** [comment]
@deblaererobin cool, ziet er naar uit dat het al meer vorm begint te krijgen. 

Tip: om user input af te handelen laat je de user best kiezen uit opties bv: [1, 2] of ook [Y, n].

Tip: Probeer ook try/catch structuur te vermijden.

Tip: Je kan userinput in 3 categorïen plaatsen:
- user kiest een correcte optie
- user kies een incorrecte optie
- user kies leeg "" en dus de default optie

**Comment by SnelleJelle** [comment]
@deblaererobin voortgang?

**Comment by SnelleJelle** [comment]
@deblaererobin voortgang?

**Comment by deblaererobin** [comment]
begint er op te trekken

**Comment by SnelleJelle** [comment]
@deblaererobin show kr

**Comment by deblaererobin** [comment]
http://pastebin.com/r5AkcSMt

**Comment by deblaererobin** [comment]
nu nog enkel alles overlopen in de file :)

**Comment by deblaererobin** [comment]
en kleine dingen fixen

**Comment by SnelleJelle** [comment]
@deblaererobin ist af?

**Comment by deblaererobin** [comment]
http://pastebin.com/WZMFmbLJ dees werkt wel niet gelijk... hij vindt geen match blijkbaar heb al gedebugged :o

**Comment by SnelleJelle** [comment]
@deblaererobin `import re` ?

**Comment by deblaererobin** [comment]
hij overloopt ze maar vind geen match

**Comment by SnelleJelle** [comment]
@deblaererobin status update?

**Comment by SnelleJelle** [comment]
regex replace:
https://gist.github.com/SnelleJelle/70415ff8eae65d46259ed096b0a06984

**Comment by deblaererobin** [comment]
http://pastebin.com/jdG7Skt2
zie comments in paste bin 

nu nog enkel alle lijnen in die file zetten :)

**Comment by deblaererobin** [comment]
oke alles werkt maar die ene regel neemt hij niet over

**Comment by deblaererobin** [comment]
IT WORKS! @SnelleJelle @Badlapje 
waar kan ik mijn script plaatsen?

**Comment by SnelleJelle** [comment]
@deblaererobin hierzo

**Comment by deblaererobin** [comment]
http://pastebin.com/JDrt2Y6F

**Comment by SnelleJelle** [comment]
@deblaererobin 
```else:
                user_input = userChoice(question, option)
            new_line = re.sub("\<[A-Za-z0-9 |,]*\>", user_input, line)
 
            new_file.write(new_line)
        else:
            new_file.write(line)
```
als je doet:
```line = re.sub("\<[A-Za-z0-9 |,]*\>", user_input, line)```
kan je twee regels afscheren

**Comment by SnelleJelle** [comment]
@deblaererobin ze de string `file_path = "D:\VagrantRoeselareVrijwilligt\PythonInstallationGuide\File\config2.yaml"` vanboven in de file

**Comment by SnelleJelle** [comment]
@deblaererobin verwijder je `print` statements

en
```
line_split = line.split("|", 3)
option = line_split[1].split(",", 2)
question = line_split[0].split("<", 2)
question = question[1]  
```
kan duidelijker geschreven worden door duidelijk aan te geven of het over enkel- of meervoud gaat en namen te gebruiken die meer specifieëren dan line_split

**Comment by deblaererobin** [comment]
@SnelleJelle wat bedoel je met de eerste comment? 

welke 2 regels wil je dan afscheren? want hij past deze niet aan in de originele file of heb je het daar niet over?

**Comment by deblaererobin** [comment]
Moet ik ook een maken in c#?
