### ISSUE TITLE
Make english translation

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#77]
create a validators.en.yml file

**Comment by MKoen** [comment]
Kan/mag ik daaraan werken?

**Comment by SnelleJelle** [comment]
@MKoen tuurlijk!

**Comment by MKoen** [comment]
Wat moet ik precies doen om hier goed aan te beginnen?

**Comment by SnelleJelle** [comment]
in `\app\Resources\translations` staat er een file: `validators.nl.yml`, maak hiervan een kopie en noem deze `validators.en.yml` daarna is het gewoon een kwestie van de waardes in de nieuwe file te vertalen.

**Comment by beuntje** [comment]
Misschien best werken in de branch "dev-languages", daar bestaat er al een
systeem waar je de taal kan prefixen in het pad  (localhost/nl/pagina of
localhost/en/pagina).

2016-05-12 10:07 GMT+02:00 Jelle Criel <notifications@github.com>:

**Comment by MKoen** [comment]
Ah had die nl nog niet staan in mijn eigen branch. Zal er aan beginnen, merci voor de uitleg

**Comment by MKoen** [comment]
Oke, zal die in de dev-languages branch steken

**Comment by SnelleJelle** [comment]
@MKoen neen, plaats deze in je eigen nieuwe branch

**Comment by MKoen** [comment]
@SnelleJelle Sorry, heb dit iets te laat gezien en heb dit op dev-languages gepushed. Hopelijk geen te groot probleem veroorzaakt?

**Comment by SnelleJelle** [comment]
@MKoen Ik zal het wel overleven. :smile:

**Comment by MKoen** [comment]
@SnelleJelle  
<img height=200 src="https://apilgrimsponderings.files.wordpress.com/2014/07/phew.jpg">

**Comment by SnelleJelle** [comment]
@MKoen ik ben enkele suggesties aan het plaatsen op je commit.
aan jou de keuze welke je beter vindt.
https://github.com/howest-wsde/VrijwilligersTool/commit/a5b52107541a7835fa769363f6ddd36d2276188c?diff=split

**Comment by MKoen** [comment]
@SnelleJelle Ok, merci. In welke branch heb je liever dat ik dat verander?

**Comment by SnelleJelle** [comment]
@MKoen doe maar verder waar je bezig bent, ik wou iets proberen maar ben er niet in geslaagd. Mijn wijzigingen gaan dus geen conflicten veroorzaken op die branch.

**Comment by MKoen** [comment]
@SnelleJelle Nieuwe versie gepushed met correcties in dev-languages

**Comment by MKoen** [comment]
@SnelleJelle Mag/kan ik ook het franse deel doen?

**Comment by SnelleJelle** [comment]
@MKoen Ja, en ook de arabische!

**Comment by MKoen** [comment]
@SnelleJelle حسنا
