### ISSUE TITLE
Google Maps marker icon

### ISSUE THREAD

**Issue by durnezj** [howest-wsde/VrijwilligersTool#81]
Find new and free to use custom icons for the google maps markers.

**Comment by Badlapje** [comment]
https://mapicons.mapsmarker.com/

**Comment by durnezj** [comment]
ik heb ze aangepast, misschien kan het icoontje van de vacature later nog aangepast worden afhankelijk van de categorie van de vacature?

**Comment by Badlapje** [comment]
geen slecht idee :-)
