### ISSUE TITLE
username can only contain valid chars

### ISSUE THREAD

**Issue by SnelleJelle** [howest-wsde/VrijwilligersTool#87]
no whitespaces in username

 - Validation and constraint in backend _(CHECK)_
 - Validation in frontend _(TODO)_

**Comment by SnelleJelle** [comment]
backend check is er

**Comment by SnelleJelle** [comment]
@MKoen Wil je een heel klein stukje javascript schrijven om dit te controleren op het registratieformulier?

**Comment by MKoen** [comment]
@SnelleJelle ok, ik zal er vanmiddag voor kijken

**Comment by MKoen** [comment]
@SnelleJelle ik heb dit gepushed in dev_KM

**Comment by MKoen** [comment]
De frontend validation is verplaatst van validation.js naar PersonType.php
