### ISSUE TITLE
zich kandidaat stellen voor een vacature

### ISSUE THREAD

**Issue by beuntje** [howest-wsde/VrijwilligersTool#88]
**jelle edit:**
de knop "stel me kandidaat" beschikbaar en functioneel maken. 
als entity met fields:
approved, ....(more to come)_

**Comment by SnelleJelle** [comment]
@beuntje closen?

**Comment by beuntje** [comment]
Er zit nog niets van controle in (2x inschrijven), maar dit kan evt later
in ander ticket
Op 4-mei-2016 16:48 schreef "Jelle Criel" <notifications@github.com>:

**Comment by SnelleJelle** [comment]
@beuntje meerdere keren inschrijven is normaal gezien niet mogelijk omdat de username en email uniek zijn.

**Comment by beuntje** [comment]
ik bedoel 1 persoon/ user kan zich 2x inschrijven op 1 vacature"

2016-05-09 9:14 GMT+02:00 Jelle Criel <notifications@github.com>:
