### ISSUE TITLE
Validatie persoon

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#89]
- zie unittests
- extra test implementeren voor contactmogelijkheden: er moet minimaal 1 van de 3 aanwezig zijn => onderste unit test in PersonTest.
- aanpassing maken aan het formulier zodat de placeholder ook toont dat je kan inloggen met email/telefoon of organisatie (niet noodzakelijk op naam)

**Comment by Badlapje** [comment]
momenteel staat email op not nullable, maar dit mag dus wel degelijk nullable zijn (!)

**Comment by SnelleJelle** [comment]
@Badlapje ^ Je hebt toch de e-mail nodig om de user te registreren?

**Comment by Badlapje** [comment]
nee: je moet minimaal 1 van 3 contactmogelijkheden hebben.  Je hebt dus of een email, of een telefoon, of een contactorganisatie nodig.  Kan dus perfect met enkel een telefoon en geen email bv.

**Comment by SnelleJelle** [comment]
@Badlapje ik ga akkoord dat **inloggen * *mogelijk is via email, telefoon of organisatie. Maar om de gebruiker te **registreren** heb je toch een direct contactmiddel nodig (uitzondering voor sociale media). 
Anders kan ik bv. iemand gaan registreren op platformen via zijn email, zonder toegang te hebben tot de inbox.

**Comment by SnelleJelle** [comment]
Placeholders in login formulier worden opgevuld met translations

**Comment by Badlapje** [comment]
da's inderdaad een concern (wel enkel voor de telefoonnummer), maar dat was wel de uitdrukkelijke vraag van de organisaties en vrijwilligers: om email niet verplicht te maken omdat een belangrijk deel van hun publiek dat niet heeft.  Ik zou het dus voorlopig implementeren zoals gevraagd en dan de concern uitleggen bij het volgende klankbordmoment.  Op papier is het te abstract voor niet-programmeurs.

**Comment by SnelleJelle** [comment]
#96

**Comment by SnelleJelle** [comment]
#107 @Badlapje
