### ISSUE TITLE
prompt user login

### ISSUE THREAD

**Issue by SnelleJelle** [howest-wsde/VrijwilligersTool#94]
...where privilege escalation is required.

- full stack implementation

**Comment by Badlapje** [comment]
ter verduidelijking: maken dat er voor acties waarvoor login verplicht is een check gebeurd en indien niet ingelogd een prompt verschijnt met daarop een mededeling + mogelijkheid om in te loggen of te registreren.

**Comment by Badlapje** [comment]
http://symfony.com/doc/current/book/security.html#checking-to-see-if-a-user-is-logged-in-is-authenticated-fully

**Comment by Badlapje** [comment]
wegens late uur vergeten om een nieuwe branch te maken, maar kon dit oplossen door 1 veld in commentaar te zetten in login.html.twig.

Er wordt nu geredirect naar de referring page, tenzij de referring page de homepage was ... in welks geval er wordt verwezen naar de mijn profiel pagina (die nog volledig moet gemaakt worden).  Route kan gecontroleerd worden in security.yml, Zie form_login, default_target_path om die route in te stellen.
